// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intellix/price/dvs_process_request.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProcessRequestPriceFeedIn defines task request from task-dispatcher
type ProcessRequestPriceFeedIn struct {
	Task      *TaskRequest    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	PriceFeed *PriceFeedParam `protobuf:"bytes,2,opt,name=price_feed,json=priceFeed,proto3" json:"price_feed,omitempty"`
}

func (m *ProcessRequestPriceFeedIn) Reset()         { *m = ProcessRequestPriceFeedIn{} }
func (m *ProcessRequestPriceFeedIn) String() string { return proto.CompactTextString(m) }
func (*ProcessRequestPriceFeedIn) ProtoMessage()    {}
func (*ProcessRequestPriceFeedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b868a4210c4bda, []int{0}
}
func (m *ProcessRequestPriceFeedIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProcessRequestPriceFeedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProcessRequestPriceFeedIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProcessRequestPriceFeedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessRequestPriceFeedIn.Merge(m, src)
}
func (m *ProcessRequestPriceFeedIn) XXX_Size() int {
	return m.Size()
}
func (m *ProcessRequestPriceFeedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessRequestPriceFeedIn.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessRequestPriceFeedIn proto.InternalMessageInfo

func (m *ProcessRequestPriceFeedIn) GetTask() *TaskRequest {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *ProcessRequestPriceFeedIn) GetPriceFeed() *PriceFeedParam {
	if m != nil {
		return m.PriceFeed
	}
	return nil
}

// ProcessRequestPriceFeedOut
type ProcessRequestPriceFeedOut struct {
	RequestId []byte `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TaskIndex uint32 `protobuf:"varint,2,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	// Aggregated final price
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	// Timestamp when aggregation was completed
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of data sources participated in aggregation
	SourceCount int32 `protobuf:"varint,5,opt,name=source_count,json=sourceCount,proto3" json:"source_count,omitempty"`
	// Number of operators participated in aggregation
	OperatorCount int32 `protobuf:"varint,6,opt,name=operator_count,json=operatorCount,proto3" json:"operator_count,omitempty"`
	// Block height at which aggregation was completed
	BlockHeight uint64 `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Block range used for aggregation
	BlockRange *BlockRange `protobuf:"bytes,8,opt,name=block_range,json=blockRange,proto3" json:"block_range,omitempty"`
}

func (m *ProcessRequestPriceFeedOut) Reset()         { *m = ProcessRequestPriceFeedOut{} }
func (m *ProcessRequestPriceFeedOut) String() string { return proto.CompactTextString(m) }
func (*ProcessRequestPriceFeedOut) ProtoMessage()    {}
func (*ProcessRequestPriceFeedOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b868a4210c4bda, []int{1}
}
func (m *ProcessRequestPriceFeedOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProcessRequestPriceFeedOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProcessRequestPriceFeedOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProcessRequestPriceFeedOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessRequestPriceFeedOut.Merge(m, src)
}
func (m *ProcessRequestPriceFeedOut) XXX_Size() int {
	return m.Size()
}
func (m *ProcessRequestPriceFeedOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessRequestPriceFeedOut.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessRequestPriceFeedOut proto.InternalMessageInfo

func (m *ProcessRequestPriceFeedOut) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *ProcessRequestPriceFeedOut) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *ProcessRequestPriceFeedOut) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProcessRequestPriceFeedOut) GetSourceCount() int32 {
	if m != nil {
		return m.SourceCount
	}
	return 0
}

func (m *ProcessRequestPriceFeedOut) GetOperatorCount() int32 {
	if m != nil {
		return m.OperatorCount
	}
	return 0
}

func (m *ProcessRequestPriceFeedOut) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ProcessRequestPriceFeedOut) GetBlockRange() *BlockRange {
	if m != nil {
		return m.BlockRange
	}
	return nil
}

// BlockRange defines the range of blocks used for price aggregation
type BlockRange struct {
	// Start block height for aggregation
	Start uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// End block height for aggregation
	End uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *BlockRange) Reset()         { *m = BlockRange{} }
func (m *BlockRange) String() string { return proto.CompactTextString(m) }
func (*BlockRange) ProtoMessage()    {}
func (*BlockRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b868a4210c4bda, []int{2}
}
func (m *BlockRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRange.Merge(m, src)
}
func (m *BlockRange) XXX_Size() int {
	return m.Size()
}
func (m *BlockRange) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRange.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRange proto.InternalMessageInfo

func (m *BlockRange) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockRange) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*ProcessRequestPriceFeedIn)(nil), "intellix.price.ProcessRequestPriceFeedIn")
	proto.RegisterType((*ProcessRequestPriceFeedOut)(nil), "intellix.price.ProcessRequestPriceFeedOut")
	proto.RegisterType((*BlockRange)(nil), "intellix.price.BlockRange")
}

func init() {
	proto.RegisterFile("intellix/price/dvs_process_request.proto", fileDescriptor_42b868a4210c4bda)
}

var fileDescriptor_42b868a4210c4bda = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0xb5, 0x1d, 0xd4, 0xed, 0x26, 0x66, 0x4d, 0x2c, 0x6b, 0x21, 0xeb, 0x8a, 0x10,
	0x61, 0x12, 0x09, 0x1d, 0x5c, 0x18, 0xe2, 0x52, 0x26, 0xa0, 0x12, 0x68, 0x95, 0xc5, 0x89, 0x4b,
	0xe4, 0x26, 0x26, 0x8d, 0xda, 0xc4, 0xc1, 0x76, 0xab, 0xed, 0x13, 0x20, 0x71, 0xe2, 0xa3, 0x70,
	0xe0, 0x43, 0x4c, 0x9c, 0x76, 0xe0, 0x80, 0x38, 0x4c, 0xa8, 0x3d, 0xf0, 0x1d, 0x38, 0x21, 0xdb,
	0x69, 0xcb, 0x3a, 0x15, 0xed, 0xd2, 0xfa, 0xfd, 0xff, 0xbf, 0x27, 0xbf, 0xe7, 0xf7, 0x02, 0xec,
	0x28, 0x11, 0x64, 0x30, 0x88, 0x8e, 0xdd, 0x94, 0x45, 0x3e, 0x71, 0x83, 0x11, 0xf7, 0x52, 0x46,
	0x7d, 0xc2, 0xb9, 0xc7, 0xc8, 0x87, 0x21, 0xe1, 0xc2, 0x49, 0x19, 0x15, 0x14, 0xae, 0x4f, 0x49,
	0x47, 0x91, 0xd5, 0xcd, 0x90, 0x86, 0x54, 0x59, 0xae, 0x3c, 0x69, 0xaa, 0xba, 0xe5, 0x53, 0x1e,
	0x53, 0xee, 0xc6, 0x3c, 0x74, 0x47, 0x4d, 0xf9, 0x97, 0x19, 0xdb, 0xda, 0xf0, 0x74, 0x86, 0x0e,
	0x32, 0x6b, 0x03, 0xc7, 0x51, 0x42, 0x5d, 0xf5, 0x3b, 0xa5, 0x17, 0xca, 0x12, 0x98, 0xf7, 0xb5,
	0xd5, 0xf8, 0x6e, 0x80, 0xed, 0x8e, 0xae, 0x10, 0xe9, 0x02, 0x3b, 0x12, 0x79, 0x41, 0x48, 0xd0,
	0x4e, 0xa0, 0x0b, 0x0a, 0x92, 0x35, 0x8d, 0xba, 0x61, 0x97, 0xf7, 0x6b, 0xce, 0xc5, 0xa2, 0x9d,
	0xb7, 0x98, 0xf7, 0xb3, 0x2c, 0xa4, 0x40, 0xf8, 0x0c, 0x00, 0x65, 0x79, 0xef, 0x09, 0x09, 0xcc,
	0x15, 0x95, 0x66, 0x2d, 0xa6, 0xcd, 0x6e, 0xe8, 0x60, 0x86, 0x63, 0x54, 0x4a, 0xa7, 0xf1, 0xc1,
	0xcb, 0x6f, 0x5f, 0x1f, 0x64, 0x3d, 0x3b, 0x5d, 0xcc, 0x89, 0x33, 0x6a, 0x76, 0x89, 0xc0, 0x4d,
	0xe7, 0x0d, 0x0f, 0x3f, 0xfd, 0xfe, 0xb2, 0x77, 0x6f, 0xd6, 0xc8, 0x3f, 0x2f, 0xec, 0x4e, 0x5f,
	0x78, 0x7e, 0x73, 0xe3, 0xcf, 0x0a, 0xa8, 0x2e, 0x69, 0xeb, 0x68, 0x28, 0xe0, 0x6d, 0x00, 0xb2,
	0x71, 0x78, 0x51, 0xa0, 0xba, 0xab, 0xa0, 0x52, 0xa6, 0xb4, 0x03, 0x69, 0xcb, 0x6e, 0xbc, 0x28,
	0x09, 0xc8, 0xb1, 0xea, 0x62, 0x0d, 0x95, 0xa4, 0xd2, 0x96, 0x02, 0x7c, 0x02, 0x8a, 0xea, 0x2a,
	0x33, 0x5f, 0x37, 0xec, 0x52, 0xeb, 0xce, 0xe9, 0xf9, 0x4e, 0xee, 0xe7, 0xf9, 0x4e, 0x4d, 0x17,
	0xce, 0x83, 0xbe, 0x13, 0x51, 0x37, 0xc6, 0xa2, 0xe7, 0xbc, 0x26, 0x21, 0xf6, 0x4f, 0x0e, 0x89,
	0x8f, 0x74, 0x06, 0xbc, 0x05, 0x4a, 0x22, 0x8a, 0x09, 0x17, 0x38, 0x4e, 0xcd, 0x42, 0xdd, 0xb0,
	0xf3, 0x68, 0x2e, 0xc0, 0x5d, 0x50, 0xe1, 0x74, 0xc8, 0x7c, 0xe2, 0xf9, 0x74, 0x98, 0x08, 0xb3,
	0x58, 0x37, 0xec, 0x22, 0x2a, 0x6b, 0xed, 0xb9, 0x94, 0xe0, 0x5d, 0xb0, 0x4e, 0x53, 0xc2, 0xb0,
	0xa0, 0x2c, 0x83, 0x56, 0x15, 0xb4, 0x36, 0x55, 0x35, 0xb6, 0x0b, 0x2a, 0xdd, 0x01, 0xf5, 0xfb,
	0x5e, 0x8f, 0x44, 0x61, 0x4f, 0x98, 0xd7, 0xea, 0x86, 0x5d, 0x40, 0x65, 0xa5, 0xbd, 0x52, 0x12,
	0x7c, 0x0a, 0x74, 0xe8, 0x31, 0x9c, 0x84, 0xc4, 0xbc, 0xae, 0x66, 0x55, 0x5d, 0x9c, 0x55, 0x4b,
	0x22, 0x48, 0x12, 0x08, 0x74, 0x67, 0xe7, 0x83, 0xda, 0x7f, 0x06, 0xd5, 0x78, 0x0c, 0xc0, 0x3c,
	0x0d, 0x6e, 0x82, 0x22, 0x17, 0x98, 0x09, 0xf5, 0xcc, 0x05, 0xa4, 0x03, 0x78, 0x03, 0xe4, 0x49,
	0xa2, 0x37, 0xa4, 0x80, 0xe4, 0x71, 0xff, 0xa3, 0x01, 0x36, 0x0e, 0x47, 0xfc, 0xe2, 0xd4, 0x20,
	0x03, 0x5b, 0x4b, 0xe6, 0x08, 0xef, 0x5f, 0xde, 0xab, 0x25, 0x7b, 0x5c, 0xdd, 0xbb, 0x22, 0x7a,
	0x34, 0x14, 0x8d, 0x5c, 0xeb, 0xe1, 0xe9, 0xd8, 0x32, 0xce, 0xc6, 0x96, 0xf1, 0x6b, 0x6c, 0x19,
	0x9f, 0x27, 0x56, 0xee, 0x6c, 0x62, 0xe5, 0x7e, 0x4c, 0xac, 0xdc, 0xbb, 0x9b, 0x97, 0xf6, 0x4f,
	0x9c, 0xa4, 0x84, 0x77, 0x57, 0xd5, 0xc7, 0xf4, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa,
	0x40, 0x31, 0xde, 0x00, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DvsProcessRequestClient is the client API for DvsProcessRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DvsProcessRequestClient interface {
	// ProcessRequestPriceFeed defines avsi logic processing
	ProcessRequestPriceFeed(ctx context.Context, in *ProcessRequestPriceFeedIn, opts ...grpc.CallOption) (*ProcessRequestPriceFeedOut, error)
}

type dvsProcessRequestClient struct {
	cc grpc1.ClientConn
}

func NewDvsProcessRequestClient(cc grpc1.ClientConn) DvsProcessRequestClient {
	return &dvsProcessRequestClient{cc}
}

func (c *dvsProcessRequestClient) ProcessRequestPriceFeed(ctx context.Context, in *ProcessRequestPriceFeedIn, opts ...grpc.CallOption) (*ProcessRequestPriceFeedOut, error) {
	out := new(ProcessRequestPriceFeedOut)
	err := c.cc.Invoke(ctx, "/intellix.price.DvsProcessRequest/ProcessRequestPriceFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DvsProcessRequestServer is the server API for DvsProcessRequest service.
type DvsProcessRequestServer interface {
	// ProcessRequestPriceFeed defines avsi logic processing
	ProcessRequestPriceFeed(context.Context, *ProcessRequestPriceFeedIn) (*ProcessRequestPriceFeedOut, error)
}

// UnimplementedDvsProcessRequestServer can be embedded to have forward compatible implementations.
type UnimplementedDvsProcessRequestServer struct {
}

func (*UnimplementedDvsProcessRequestServer) ProcessRequestPriceFeed(ctx context.Context, req *ProcessRequestPriceFeedIn) (*ProcessRequestPriceFeedOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessRequestPriceFeed not implemented")
}

func RegisterDvsProcessRequestServer(s grpc1.Server, srv DvsProcessRequestServer) {
	s.RegisterService(&_DvsProcessRequest_serviceDesc, srv)
}

func _DvsProcessRequest_ProcessRequestPriceFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequestPriceFeedIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DvsProcessRequestServer).ProcessRequestPriceFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intellix.price.DvsProcessRequest/ProcessRequestPriceFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DvsProcessRequestServer).ProcessRequestPriceFeed(ctx, req.(*ProcessRequestPriceFeedIn))
	}
	return interceptor(ctx, in, info, handler)
}

var DvsProcessRequest_serviceDesc = _DvsProcessRequest_serviceDesc
var _DvsProcessRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intellix.price.DvsProcessRequest",
	HandlerType: (*DvsProcessRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRequestPriceFeed",
			Handler:    _DvsProcessRequest_ProcessRequestPriceFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intellix/price/dvs_process_request.proto",
}

func (m *ProcessRequestPriceFeedIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProcessRequestPriceFeedIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProcessRequestPriceFeedIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PriceFeed != nil {
		{
			size, err := m.PriceFeed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDvsProcessRequest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Task != nil {
		{
			size, err := m.Task.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDvsProcessRequest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProcessRequestPriceFeedOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProcessRequestPriceFeedOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProcessRequestPriceFeedOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockRange != nil {
		{
			size, err := m.BlockRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDvsProcessRequest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.BlockHeight != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.OperatorCount != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.OperatorCount))
		i--
		dAtA[i] = 0x30
	}
	if m.SourceCount != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.SourceCount))
		i--
		dAtA[i] = 0x28
	}
	if m.Timestamp != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.TaskIndex != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BlockRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.End != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x10
	}
	if m.Start != 0 {
		i = encodeVarintDvsProcessRequest(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDvsProcessRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovDvsProcessRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProcessRequestPriceFeedIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Task != nil {
		l = m.Task.Size()
		n += 1 + l + sovDvsProcessRequest(uint64(l))
	}
	if m.PriceFeed != nil {
		l = m.PriceFeed.Size()
		n += 1 + l + sovDvsProcessRequest(uint64(l))
	}
	return n
}

func (m *ProcessRequestPriceFeedOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovDvsProcessRequest(uint64(l))
	}
	if m.TaskIndex != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.TaskIndex))
	}
	l = m.Price.Size()
	n += 1 + l + sovDvsProcessRequest(uint64(l))
	if m.Timestamp != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.Timestamp))
	}
	if m.SourceCount != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.SourceCount))
	}
	if m.OperatorCount != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.OperatorCount))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.BlockHeight))
	}
	if m.BlockRange != nil {
		l = m.BlockRange.Size()
		n += 1 + l + sovDvsProcessRequest(uint64(l))
	}
	return n
}

func (m *BlockRange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Start != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovDvsProcessRequest(uint64(m.End))
	}
	return n
}

func sovDvsProcessRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDvsProcessRequest(x uint64) (n int) {
	return sovDvsProcessRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProcessRequestPriceFeedIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvsProcessRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProcessRequestPriceFeedIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProcessRequestPriceFeedIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Task", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Task == nil {
				m.Task = &TaskRequest{}
			}
			if err := m.Task.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceFeed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PriceFeed == nil {
				m.PriceFeed = &PriceFeedParam{}
			}
			if err := m.PriceFeed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDvsProcessRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProcessRequestPriceFeedOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvsProcessRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProcessRequestPriceFeedOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProcessRequestPriceFeedOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = append(m.RequestId[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestId == nil {
				m.RequestId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceCount", wireType)
			}
			m.SourceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorCount", wireType)
			}
			m.OperatorCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OperatorCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockRange == nil {
				m.BlockRange = &BlockRange{}
			}
			if err := m.BlockRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDvsProcessRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvsProcessRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDvsProcessRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvsProcessRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDvsProcessRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDvsProcessRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDvsProcessRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDvsProcessRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDvsProcessRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDvsProcessRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDvsProcessRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDvsProcessRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDvsProcessRequest = fmt.Errorf("proto: unexpected end of group")
)
