version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake

task_dispatcher:
  eth_url: http://127.0.0.1:8545
  contract_address: 0x0000000000000000000000000000000000000000

build:
  main: ./cmd/intellixd