// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intellix/processor/vote_request_processor.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgVoteRequestProcessor struct {
	TaskIndex                 uint32                `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	RequestId                 []byte                `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FeeToken                  string                `protobuf:"bytes,3,opt,name=fee_token,json=feeToken,proto3" json:"fee_token,omitempty"`
	Payment                   cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=payment,proto3,customtype=cosmossdk.io/math.Int" json:"payment"`
	RequestData               []byte                `protobuf:"bytes,5,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
	CallbackAddress           string                `protobuf:"bytes,6,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"`
	CallbackFunctionId        []byte                `protobuf:"bytes,7,opt,name=callback_function_id,json=callbackFunctionId,proto3" json:"callback_function_id,omitempty"`
	TaskCreatedBlock          uint32                `protobuf:"varint,8,opt,name=task_created_block,json=taskCreatedBlock,proto3" json:"task_created_block,omitempty"`
	QuorumNumbers             []byte                `protobuf:"bytes,9,opt,name=quorum_numbers,json=quorumNumbers,proto3" json:"quorum_numbers,omitempty"`
	QuorumThresholdPercentage uint32                `protobuf:"varint,10,opt,name=quorum_threshold_percentage,json=quorumThresholdPercentage,proto3" json:"quorum_threshold_percentage,omitempty"`
	ScriptId                  uint64                `protobuf:"varint,11,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	ScriptResp                []byte                `protobuf:"bytes,12,opt,name=script_resp,json=scriptResp,proto3" json:"script_resp,omitempty"`
}

func (m *MsgVoteRequestProcessor) Reset()         { *m = MsgVoteRequestProcessor{} }
func (m *MsgVoteRequestProcessor) String() string { return proto.CompactTextString(m) }
func (*MsgVoteRequestProcessor) ProtoMessage()    {}
func (*MsgVoteRequestProcessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_24935736fa0614a3, []int{0}
}
func (m *MsgVoteRequestProcessor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteRequestProcessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteRequestProcessor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteRequestProcessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteRequestProcessor.Merge(m, src)
}
func (m *MsgVoteRequestProcessor) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteRequestProcessor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteRequestProcessor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteRequestProcessor proto.InternalMessageInfo

func (m *MsgVoteRequestProcessor) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *MsgVoteRequestProcessor) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *MsgVoteRequestProcessor) GetFeeToken() string {
	if m != nil {
		return m.FeeToken
	}
	return ""
}

func (m *MsgVoteRequestProcessor) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *MsgVoteRequestProcessor) GetCallbackAddress() string {
	if m != nil {
		return m.CallbackAddress
	}
	return ""
}

func (m *MsgVoteRequestProcessor) GetCallbackFunctionId() []byte {
	if m != nil {
		return m.CallbackFunctionId
	}
	return nil
}

func (m *MsgVoteRequestProcessor) GetTaskCreatedBlock() uint32 {
	if m != nil {
		return m.TaskCreatedBlock
	}
	return 0
}

func (m *MsgVoteRequestProcessor) GetQuorumNumbers() []byte {
	if m != nil {
		return m.QuorumNumbers
	}
	return nil
}

func (m *MsgVoteRequestProcessor) GetQuorumThresholdPercentage() uint32 {
	if m != nil {
		return m.QuorumThresholdPercentage
	}
	return 0
}

func (m *MsgVoteRequestProcessor) GetScriptId() uint64 {
	if m != nil {
		return m.ScriptId
	}
	return 0
}

func (m *MsgVoteRequestProcessor) GetScriptResp() []byte {
	if m != nil {
		return m.ScriptResp
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgVoteRequestProcessor)(nil), "intellix.processor.MsgVoteRequestProcessor")
}

func init() {
	proto.RegisterFile("intellix/processor/vote_request_processor.proto", fileDescriptor_24935736fa0614a3)
}

var fileDescriptor_24935736fa0614a3 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x18, 0xdb, 0xea, 0x76, 0x30, 0xac, 0xa1, 0x65, 0x9d, 0x96, 0x96, 0x49, 0xa0,
	0x82, 0x20, 0xa1, 0x02, 0x09, 0x89, 0x03, 0x12, 0x05, 0x21, 0xf5, 0x30, 0x34, 0x45, 0x13, 0x07,
	0x2e, 0x91, 0x13, 0xbf, 0x4d, 0xa3, 0x26, 0x76, 0x66, 0xbb, 0xd5, 0x76, 0xe5, 0x13, 0xf0, 0x31,
	0x38, 0x72, 0xe0, 0x43, 0x4c, 0x9c, 0x76, 0x44, 0x1c, 0x26, 0xd4, 0x1e, 0xf8, 0x1a, 0xc8, 0x76,
	0x52, 0x81, 0xb4, 0x4b, 0x12, 0xff, 0x9e, 0xc7, 0xef, 0xbf, 0xbc, 0x28, 0xc8, 0x98, 0x82, 0x3c,
	0xcf, 0xce, 0x82, 0x52, 0xf0, 0x04, 0xa4, 0xe4, 0x22, 0x98, 0x73, 0x05, 0x91, 0x80, 0xd3, 0x19,
	0x48, 0x15, 0xad, 0xb0, 0x5f, 0x0a, 0xae, 0x38, 0xc6, 0xf5, 0x05, 0x7f, 0xa5, 0x74, 0xee, 0x92,
	0x22, 0x63, 0x3c, 0x30, 0x4f, 0x6b, 0xeb, 0xec, 0x26, 0x5c, 0x16, 0x5c, 0x06, 0x85, 0x4c, 0x83,
	0xf9, 0x40, 0xbf, 0x2a, 0x61, 0xcf, 0x0a, 0x91, 0x39, 0x05, 0xf6, 0x50, 0x49, 0x3b, 0x29, 0x4f,
	0xb9, 0xe5, 0xfa, 0xab, 0xa2, 0xdd, 0x6b, 0x2a, 0x2c, 0x89, 0x20, 0x45, 0x7d, 0xed, 0xf0, 0x3a,
	0xc3, 0xff, 0x55, 0x1f, 0x7e, 0x5d, 0x43, 0xbb, 0x47, 0x32, 0xfd, 0xc8, 0x15, 0x84, 0xb6, 0xb1,
	0xe3, 0xda, 0x81, 0x0f, 0x10, 0x52, 0x44, 0x4e, 0xa3, 0x8c, 0x51, 0x38, 0x73, 0x9d, 0x9e, 0xd3,
	0xdf, 0x0a, 0x9b, 0x9a, 0x8c, 0x34, 0xd0, 0x72, 0x3d, 0x8b, 0x8c, 0xba, 0x37, 0x7a, 0x4e, 0xbf,
	0x1d, 0x36, 0x2b, 0x32, 0xa2, 0x78, 0x1f, 0x35, 0xc7, 0x00, 0x91, 0xe2, 0x53, 0x60, 0xee, 0xcd,
	0x9e, 0xd3, 0x6f, 0x86, 0x9b, 0x63, 0x80, 0x13, 0x7d, 0xc6, 0x2f, 0xd1, 0x46, 0x49, 0xce, 0x0b,
	0x60, 0xca, 0x5d, 0xd3, 0xd2, 0xf0, 0xe0, 0xe2, 0xaa, 0xdb, 0xf8, 0x75, 0xd5, 0xbd, 0x67, 0x1b,
	0x97, 0x74, 0xea, 0x67, 0x3c, 0x28, 0x88, 0x9a, 0xf8, 0x23, 0xa6, 0xc2, 0xda, 0x8d, 0xef, 0xa3,
	0x76, 0x9d, 0x94, 0x12, 0x45, 0xdc, 0x5b, 0x26, 0x6d, 0xab, 0x62, 0xef, 0x88, 0x22, 0xf8, 0x11,
	0xda, 0x4e, 0x48, 0x9e, 0xc7, 0x24, 0x99, 0x46, 0x84, 0x52, 0x01, 0x52, 0xba, 0xeb, 0x26, 0xff,
	0x9d, 0x9a, 0xbf, 0xb1, 0x18, 0x3f, 0x43, 0x3b, 0x2b, 0xeb, 0x78, 0xc6, 0x12, 0x95, 0x71, 0xa6,
	0x9b, 0xd9, 0x30, 0x51, 0x71, 0xad, 0xbd, 0xaf, 0xa4, 0x11, 0xc5, 0x4f, 0x10, 0x36, 0x33, 0x49,
	0x04, 0x10, 0x05, 0x34, 0x8a, 0x73, 0x9e, 0x4c, 0xdd, 0x4d, 0x33, 0x9b, 0x6d, 0xad, 0xbc, 0xb5,
	0xc2, 0x50, 0x73, 0xfc, 0x00, 0xdd, 0x3e, 0x9d, 0x71, 0x31, 0x2b, 0x22, 0x36, 0x2b, 0x62, 0x10,
	0xd2, 0x6d, 0x9a, 0xc8, 0x5b, 0x96, 0x7e, 0xb0, 0x10, 0xbf, 0x46, 0xfb, 0x95, 0x4d, 0x4d, 0x04,
	0xc8, 0x09, 0xcf, 0x69, 0x54, 0x82, 0x48, 0x80, 0x29, 0x92, 0x82, 0x8b, 0x4c, 0xf4, 0x3d, 0x6b,
	0x39, 0xa9, 0x1d, 0xc7, 0x2b, 0x83, 0x1e, 0xb5, 0x4c, 0x44, 0x56, 0x9a, 0x1f, 0xd1, 0xea, 0x39,
	0xfd, 0xb5, 0x70, 0xd3, 0x82, 0x11, 0xc5, 0x5d, 0xd4, 0xaa, 0x44, 0x01, 0xb2, 0x74, 0xdb, 0xa6,
	0x00, 0x64, 0x51, 0x08, 0xb2, 0x7c, 0xf5, 0xf0, 0xc7, 0xf7, 0xa7, 0xd5, 0x56, 0xfa, 0x31, 0x91,
	0xe0, 0xcf, 0x07, 0x31, 0x28, 0x32, 0xf0, 0x8f, 0x64, 0xfa, 0xf9, 0xcf, 0xb7, 0xc7, 0xeb, 0x12,
	0x18, 0x05, 0x31, 0x7c, 0x71, 0xb1, 0xf0, 0x9c, 0xcb, 0x85, 0xe7, 0xfc, 0x5e, 0x78, 0xce, 0x97,
	0xa5, 0xd7, 0xb8, 0x5c, 0x7a, 0x8d, 0x9f, 0x4b, 0xaf, 0xf1, 0xa9, 0xb3, 0x5a, 0xb4, 0x7f, 0x57,
	0x4d, 0x9d, 0x97, 0x20, 0xe3, 0x75, 0xb3, 0x67, 0xcf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0x27, 0x28, 0xab, 0x50, 0x03, 0x00, 0x00,
}

func (m *MsgVoteRequestProcessor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteRequestProcessor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteRequestProcessor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ScriptResp) > 0 {
		i -= len(m.ScriptResp)
		copy(dAtA[i:], m.ScriptResp)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.ScriptResp)))
		i--
		dAtA[i] = 0x62
	}
	if m.ScriptId != 0 {
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(m.ScriptId))
		i--
		dAtA[i] = 0x58
	}
	if m.QuorumThresholdPercentage != 0 {
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(m.QuorumThresholdPercentage))
		i--
		dAtA[i] = 0x50
	}
	if len(m.QuorumNumbers) > 0 {
		i -= len(m.QuorumNumbers)
		copy(dAtA[i:], m.QuorumNumbers)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.QuorumNumbers)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TaskCreatedBlock != 0 {
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(m.TaskCreatedBlock))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CallbackFunctionId) > 0 {
		i -= len(m.CallbackFunctionId)
		copy(dAtA[i:], m.CallbackFunctionId)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.CallbackFunctionId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CallbackAddress) > 0 {
		i -= len(m.CallbackAddress)
		copy(dAtA[i:], m.CallbackAddress)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.CallbackAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequestData) > 0 {
		i -= len(m.RequestData)
		copy(dAtA[i:], m.RequestData)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.RequestData)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.Payment.Size()
		i -= size
		if _, err := m.Payment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.FeeToken) > 0 {
		i -= len(m.FeeToken)
		copy(dAtA[i:], m.FeeToken)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.FeeToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskIndex != 0 {
		i = encodeVarintVoteRequestProcessor(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteRequestProcessor(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteRequestProcessor(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgVoteRequestProcessor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovVoteRequestProcessor(uint64(m.TaskIndex))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	l = len(m.FeeToken)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	l = m.Payment.Size()
	n += 1 + l + sovVoteRequestProcessor(uint64(l))
	l = len(m.RequestData)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	l = len(m.CallbackAddress)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	l = len(m.CallbackFunctionId)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	if m.TaskCreatedBlock != 0 {
		n += 1 + sovVoteRequestProcessor(uint64(m.TaskCreatedBlock))
	}
	l = len(m.QuorumNumbers)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	if m.QuorumThresholdPercentage != 0 {
		n += 1 + sovVoteRequestProcessor(uint64(m.QuorumThresholdPercentage))
	}
	if m.ScriptId != 0 {
		n += 1 + sovVoteRequestProcessor(uint64(m.ScriptId))
	}
	l = len(m.ScriptResp)
	if l > 0 {
		n += 1 + l + sovVoteRequestProcessor(uint64(l))
	}
	return n
}

func sovVoteRequestProcessor(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteRequestProcessor(x uint64) (n int) {
	return sovVoteRequestProcessor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgVoteRequestProcessor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteRequestProcessor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteRequestProcessor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteRequestProcessor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = append(m.RequestId[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestId == nil {
				m.RequestId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestData = append(m.RequestData[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestData == nil {
				m.RequestData = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackFunctionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackFunctionId = append(m.CallbackFunctionId[:0], dAtA[iNdEx:postIndex]...)
			if m.CallbackFunctionId == nil {
				m.CallbackFunctionId = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskCreatedBlock", wireType)
			}
			m.TaskCreatedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskCreatedBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumNumbers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuorumNumbers = append(m.QuorumNumbers[:0], dAtA[iNdEx:postIndex]...)
			if m.QuorumNumbers == nil {
				m.QuorumNumbers = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumThresholdPercentage", wireType)
			}
			m.QuorumThresholdPercentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuorumThresholdPercentage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptId", wireType)
			}
			m.ScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScriptId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptResp", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptResp = append(m.ScriptResp[:0], dAtA[iNdEx:postIndex]...)
			if m.ScriptResp == nil {
				m.ScriptResp = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteRequestProcessor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteRequestProcessor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteRequestProcessor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteRequestProcessor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteRequestProcessor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteRequestProcessor
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteRequestProcessor
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteRequestProcessor
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteRequestProcessor        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteRequestProcessor          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteRequestProcessor = fmt.Errorf("proto: unexpected end of group")
)
