FROM pellnode:latest AS pell
FROM node:18

ARG GITHUB_TOKEN
ARG HTTP_PROXY
ARG HTTPS_PROXY

RUN apt-get update -yqq && apt-get install -yqq openssh-server iputils-ping lsof net-tools curl vim-common jq tree
RUN echo "alias ls='ls --color' " >> ~/.bashrc && echo "alias ll='ls -l' " >> ~/.bashrc

RUN curl -L https://foundry.paradigm.xyz | bash
RUN npm install --global hardhat-shorthand

COPY scripts/hh/hh.bash /root/.config/tabtab/bash/hh.bash
COPY scripts/hh/__tabtab.bash /root/.config/tabtab/bash/__tabtab.bash
RUN mkdir -p /root/.config/tabtab/bash && echo "source /root/.config/tabtab/bash/__tabtab.bash" >> ~/.bashrc

# Download foundry
ENV PATH="$PATH:/root/.foundry/bin"
RUN foundryup

WORKDIR /app

RUN <<EOR
	git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
	git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"
EOR

RUN git clone https://github.com/IntelliXLabs/price-oracle-dvs.git --branch v0.1.1 --depth 1

WORKDIR /app/price-oracle-dvs
ADD .env .env

# install deps
RUN yarn install --frozen-lockfile && forge install
RUN forge compile && npx hardhat compile

# expose port
EXPOSE 8545
EXPOSE 22

# run hardhat node
CMD ./scripts/docker_init.sh

