FROM pellnode:latest AS pell
FROM node:18

ARG HTTP_PROXY
ARG HTTPS_PROXY

# Download foundry
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="$PATH:/root/.foundry/bin"
RUN foundryup

RUN apt-get update -yqq && apt-get install -yqq openssh-server iputils-ping lsof net-tools curl vim-common jq

WORKDIR /app
ARG GITHUB_TOKEN

RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"

RUN git clone https://github.com/IntelliXLabs/price-oracle-dvs.git --branch main --depth 1

WORKDIR /app/price-oracle-dvs

ADD .env .env

# install deps
RUN yarn install --frozen-lockfile && forge install
RUN forge compile && npx hardhat compile

# expose port
EXPOSE 8545
EXPOSE 22

# run hardhat node
ADD scripts/docker_init_local.sh ./scripts/docker_init_local.sh
CMD ./scripts/docker_init_local.sh

