FROM pellnode:latest AS pell
FROM node:18

ARG GITHUB_TOKEN
ARG HTTP_PROXY
ARG HTTPS_PROXY

RUN apt-get update -yqq && apt-get install -yqq openssh-server iputils-ping lsof net-tools curl vim-common jq tree expect
RUN echo "alias ls='ls --color' " >> ~/.bashrc && echo "alias ll='ls -l' " >> ~/.bashrc
RUN npm install --global hardhat-shorthand
COPY scripts/install_hardhat_completion.sh /tmp/install_hardhat_completion.sh
RUN /tmp/install_hardhat_completion.sh

# Download foundry
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="$PATH:/root/.foundry/bin"
RUN foundryup

RUN <<EOR
	git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
	git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"
EOR

WORKDIR /app

RUN git clone https://github.com/IntelliXLabs/price-oracle-dvs.git --branch v0.1.2 --depth 1

WORKDIR /app/price-oracle-dvs
ADD .env .env

# install deps
RUN yarn install --frozen-lockfile && forge install
RUN forge compile && npx hardhat compile

# expose port
EXPOSE 8545
EXPOSE 22

# run hardhat node
CMD ./scripts/docker_init.sh

