// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intellix/price/vote_finalized_request_price.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "intellix/pkg/pelldvs/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgVoteFinalizedRequestPrice struct {
	TaskRaw           *TaskRaw                               `protobuf:"bytes,1,opt,name=task_raw,json=taskRaw,proto3" json:"task_raw,omitempty"`
	ValidatedData     *types.RequestPostRequestValidatedData `protobuf:"bytes,2,opt,name=validated_data,json=validatedData,proto3" json:"validated_data,omitempty"`
	PriceFeedResponse *PriceFeedResponse                     `protobuf:"bytes,3,opt,name=price_feed_response,json=priceFeedResponse,proto3" json:"price_feed_response,omitempty"`
}

func (m *MsgVoteFinalizedRequestPrice) Reset()         { *m = MsgVoteFinalizedRequestPrice{} }
func (m *MsgVoteFinalizedRequestPrice) String() string { return proto.CompactTextString(m) }
func (*MsgVoteFinalizedRequestPrice) ProtoMessage()    {}
func (*MsgVoteFinalizedRequestPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10c75b86a03273a, []int{0}
}
func (m *MsgVoteFinalizedRequestPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteFinalizedRequestPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteFinalizedRequestPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteFinalizedRequestPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteFinalizedRequestPrice.Merge(m, src)
}
func (m *MsgVoteFinalizedRequestPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteFinalizedRequestPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteFinalizedRequestPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteFinalizedRequestPrice proto.InternalMessageInfo

func (m *MsgVoteFinalizedRequestPrice) GetTaskRaw() *TaskRaw {
	if m != nil {
		return m.TaskRaw
	}
	return nil
}

func (m *MsgVoteFinalizedRequestPrice) GetValidatedData() *types.RequestPostRequestValidatedData {
	if m != nil {
		return m.ValidatedData
	}
	return nil
}

func (m *MsgVoteFinalizedRequestPrice) GetPriceFeedResponse() *PriceFeedResponse {
	if m != nil {
		return m.PriceFeedResponse
	}
	return nil
}

type TaskRaw struct {
	TaskIndex                 uint32                `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	RequestId                 []byte                `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FeeToken                  string                `protobuf:"bytes,3,opt,name=fee_token,json=feeToken,proto3" json:"fee_token,omitempty"`
	Payment                   cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=payment,proto3,customtype=cosmossdk.io/math.Int" json:"payment"`
	RequestData               []byte                `protobuf:"bytes,5,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
	CallbackAddress           string                `protobuf:"bytes,6,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"`
	CallbackFunctionId        []byte                `protobuf:"bytes,7,opt,name=callback_function_id,json=callbackFunctionId,proto3" json:"callback_function_id,omitempty"`
	TaskCreatedBlock          uint32                `protobuf:"varint,8,opt,name=task_created_block,json=taskCreatedBlock,proto3" json:"task_created_block,omitempty"`
	QuorumNumbers             []byte                `protobuf:"bytes,9,opt,name=quorum_numbers,json=quorumNumbers,proto3" json:"quorum_numbers,omitempty"`
	QuorumThresholdPercentage uint32                `protobuf:"varint,10,opt,name=quorum_threshold_percentage,json=quorumThresholdPercentage,proto3" json:"quorum_threshold_percentage,omitempty"`
}

func (m *TaskRaw) Reset()         { *m = TaskRaw{} }
func (m *TaskRaw) String() string { return proto.CompactTextString(m) }
func (*TaskRaw) ProtoMessage()    {}
func (*TaskRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10c75b86a03273a, []int{1}
}
func (m *TaskRaw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskRaw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRaw.Merge(m, src)
}
func (m *TaskRaw) XXX_Size() int {
	return m.Size()
}
func (m *TaskRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRaw.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRaw proto.InternalMessageInfo

func (m *TaskRaw) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *TaskRaw) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *TaskRaw) GetFeeToken() string {
	if m != nil {
		return m.FeeToken
	}
	return ""
}

func (m *TaskRaw) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *TaskRaw) GetCallbackAddress() string {
	if m != nil {
		return m.CallbackAddress
	}
	return ""
}

func (m *TaskRaw) GetCallbackFunctionId() []byte {
	if m != nil {
		return m.CallbackFunctionId
	}
	return nil
}

func (m *TaskRaw) GetTaskCreatedBlock() uint32 {
	if m != nil {
		return m.TaskCreatedBlock
	}
	return 0
}

func (m *TaskRaw) GetQuorumNumbers() []byte {
	if m != nil {
		return m.QuorumNumbers
	}
	return nil
}

func (m *TaskRaw) GetQuorumThresholdPercentage() uint32 {
	if m != nil {
		return m.QuorumThresholdPercentage
	}
	return 0
}

type PriceFeedResponse struct {
	ReferenceTaskIndex uint32                `protobuf:"varint,1,opt,name=reference_task_index,json=referenceTaskIndex,proto3" json:"reference_task_index,omitempty"`
	Price              cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=price,proto3,customtype=cosmossdk.io/math.Int" json:"price"`
}

func (m *PriceFeedResponse) Reset()         { *m = PriceFeedResponse{} }
func (m *PriceFeedResponse) String() string { return proto.CompactTextString(m) }
func (*PriceFeedResponse) ProtoMessage()    {}
func (*PriceFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10c75b86a03273a, []int{2}
}
func (m *PriceFeedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceFeedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceFeedResponse.Merge(m, src)
}
func (m *PriceFeedResponse) XXX_Size() int {
	return m.Size()
}
func (m *PriceFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceFeedResponse proto.InternalMessageInfo

func (m *PriceFeedResponse) GetReferenceTaskIndex() uint32 {
	if m != nil {
		return m.ReferenceTaskIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgVoteFinalizedRequestPrice)(nil), "intellix.price.MsgVoteFinalizedRequestPrice")
	proto.RegisterType((*TaskRaw)(nil), "intellix.price.TaskRaw")
	proto.RegisterType((*PriceFeedResponse)(nil), "intellix.price.PriceFeedResponse")
}

func init() {
	proto.RegisterFile("intellix/price/vote_finalized_request_price.proto", fileDescriptor_b10c75b86a03273a)
}

var fileDescriptor_b10c75b86a03273a = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdd, 0x4e, 0xd4, 0x4c,
	0x18, 0xde, 0x85, 0x0f, 0x96, 0x1d, 0x7e, 0x3e, 0x18, 0x51, 0x0a, 0x48, 0x11, 0x12, 0x13, 0x4d,
	0xb4, 0x65, 0xe1, 0xc0, 0xc4, 0x03, 0x13, 0xd1, 0x90, 0xec, 0x01, 0x06, 0x9b, 0x0d, 0x31, 0x9e,
	0x4c, 0x66, 0x3b, 0xef, 0x2e, 0xcd, 0x76, 0x3b, 0xa5, 0x33, 0x5b, 0x7e, 0xae, 0xc2, 0x0b, 0xf0,
	0x2a, 0x8c, 0x17, 0x41, 0x3c, 0xe2, 0xd0, 0x78, 0x40, 0x0c, 0xdc, 0x88, 0x99, 0x77, 0xda, 0x06,
	0xe1, 0xc0, 0xa3, 0xce, 0x3c, 0xcf, 0xfb, 0xf7, 0xbc, 0x4f, 0x87, 0xb4, 0xa2, 0x44, 0x43, 0x1c,
	0x47, 0xa7, 0x7e, 0x9a, 0x45, 0x21, 0xf8, 0xb9, 0xd4, 0xc0, 0x7a, 0x51, 0xc2, 0xe3, 0xe8, 0x1c,
	0x04, 0xcb, 0xe0, 0x78, 0x04, 0x4a, 0x33, 0x24, 0xbd, 0x34, 0x93, 0x5a, 0xd2, 0xb9, 0x32, 0xc5,
	0x43, 0x74, 0x65, 0xb1, 0x2f, 0xfb, 0x12, 0x29, 0xdf, 0x9c, 0x6c, 0xd4, 0x8a, 0x1b, 0x4a, 0x35,
	0x94, 0xca, 0xef, 0x72, 0x05, 0x7e, 0xde, 0xea, 0x82, 0xe6, 0x2d, 0x3f, 0x94, 0x51, 0x52, 0xf0,
	0x4b, 0x05, 0x3f, 0x54, 0x7d, 0x3f, 0x6f, 0x99, 0x4f, 0x41, 0x2c, 0x5b, 0x82, 0xd9, 0x8a, 0xf6,
	0x52, 0x52, 0x77, 0x86, 0xd5, 0x5c, 0x0d, 0x0a, 0xea, 0x96, 0x0e, 0x88, 0x63, 0x91, 0x2b, 0x5f,
	0xe4, 0x8a, 0xa5, 0x12, 0x67, 0x97, 0x21, 0x28, 0xc5, 0x72, 0x1e, 0x47, 0x82, 0x6b, 0x10, 0x36,
	0x65, 0xf3, 0xeb, 0x18, 0x79, 0xbc, 0xaf, 0xfa, 0x87, 0x52, 0xc3, 0x5e, 0x29, 0x38, 0xb0, 0x7a,
	0x0f, 0x4c, 0x79, 0xba, 0x4d, 0xa6, 0x4c, 0x07, 0x96, 0xf1, 0x13, 0xa7, 0xfe, 0xa4, 0xfe, 0x6c,
	0x7a, 0x7b, 0xc9, 0xfb, 0x5b, 0xbb, 0xd7, 0xe1, 0x6a, 0x10, 0xf0, 0x93, 0xa0, 0xa1, 0xed, 0x81,
	0x7e, 0x22, 0x73, 0x55, 0x1f, 0x26, 0xb8, 0xe6, 0xce, 0x18, 0x66, 0xb6, 0x6e, 0x65, 0xda, 0x01,
	0xbd, 0xb2, 0x97, 0x54, 0xba, 0x38, 0x1e, 0x96, 0x99, 0xef, 0xb9, 0xe6, 0xc1, 0x6c, 0x7e, 0xfb,
	0x4a, 0x3f, 0x92, 0x07, 0xd8, 0x93, 0xf5, 0x00, 0x8d, 0x51, 0xa9, 0x4c, 0x14, 0x38, 0xe3, 0x58,
	0x7e, 0xe3, 0xee, 0x60, 0xa8, 0x60, 0x0f, 0x8c, 0x22, 0x1b, 0x18, 0x2c, 0xa4, 0x77, 0xa1, 0xd7,
	0xab, 0x3f, 0xbe, 0xbf, 0x2c, 0x7c, 0xf0, 0x8c, 0x4f, 0x5e, 0xe1, 0x93, 0xb7, 0xaf, 0xfa, 0x9b,
	0xdf, 0xc6, 0x49, 0xa3, 0x90, 0x47, 0xd7, 0x08, 0xc1, 0x4d, 0x44, 0x89, 0x80, 0x53, 0xdc, 0xc5,
	0x6c, 0xd0, 0x34, 0x48, 0xdb, 0x00, 0x86, 0x2e, 0x7f, 0x94, 0x48, 0xa0, 0xe0, 0x99, 0xa0, 0x59,
	0x20, 0x6d, 0x41, 0x57, 0x49, 0xb3, 0x07, 0xc0, 0xb4, 0x1c, 0x40, 0x82, 0xf3, 0x36, 0x83, 0xa9,
	0x1e, 0x40, 0xc7, 0xdc, 0xe9, 0x2b, 0xd2, 0x48, 0xf9, 0xd9, 0x10, 0x12, 0xed, 0xfc, 0x67, 0xa8,
	0xdd, 0xb5, 0x8b, 0xab, 0xf5, 0xda, 0xaf, 0xab, 0xf5, 0x87, 0x76, 0x30, 0x25, 0x06, 0x5e, 0x24,
	0xfd, 0x21, 0xd7, 0x47, 0x5e, 0x3b, 0xd1, 0x41, 0x19, 0x4d, 0x37, 0xc8, 0x4c, 0xd9, 0x14, 0xf7,
	0x3c, 0x81, 0x6d, 0xa7, 0x0b, 0x0c, 0x57, 0xf6, 0x9c, 0xcc, 0x87, 0x3c, 0x8e, 0xbb, 0x3c, 0x1c,
	0x30, 0x2e, 0x44, 0x06, 0x4a, 0x39, 0x93, 0xd8, 0xff, 0xff, 0x12, 0x7f, 0x6b, 0x61, 0xba, 0x45,
	0x16, 0xab, 0xd0, 0xde, 0x28, 0x09, 0x75, 0x24, 0x13, 0x23, 0xa6, 0x81, 0x55, 0x69, 0xc9, 0xed,
	0x15, 0x54, 0x5b, 0xd0, 0x17, 0x84, 0xe2, 0x4e, 0xc2, 0x0c, 0xd0, 0xec, 0x6e, 0x2c, 0xc3, 0x81,
	0x33, 0x85, 0xbb, 0x99, 0x37, 0xcc, 0x3b, 0x4b, 0xec, 0x1a, 0x9c, 0x3e, 0x25, 0x73, 0xc7, 0x23,
	0x99, 0x8d, 0x86, 0x2c, 0x19, 0x0d, 0xbb, 0x90, 0x29, 0xa7, 0x89, 0x95, 0x67, 0x2d, 0xfa, 0xc1,
	0x82, 0xf4, 0x0d, 0x59, 0x2d, 0xc2, 0xf4, 0x51, 0x06, 0xea, 0x48, 0xc6, 0x82, 0xa5, 0x90, 0x85,
	0x90, 0x68, 0xde, 0x07, 0x87, 0x60, 0xf5, 0x65, 0x1b, 0xd2, 0x29, 0x23, 0x0e, 0xaa, 0x80, 0xcd,
	0x73, 0xb2, 0x70, 0xcf, 0x79, 0xa3, 0x2d, 0x83, 0x1e, 0x64, 0x90, 0x84, 0xc0, 0xee, 0xf9, 0x48,
	0x2b, 0xae, 0x53, 0x19, 0xba, 0x43, 0x26, 0xf0, 0x6f, 0xb1, 0x5e, 0xfe, 0xcb, 0x12, 0x1b, 0xbb,
	0xbb, 0x75, 0x71, 0xed, 0xd6, 0x2f, 0xaf, 0xdd, 0xfa, 0xef, 0x6b, 0xb7, 0xfe, 0xe5, 0xc6, 0xad,
	0x5d, 0xde, 0xb8, 0xb5, 0x9f, 0x37, 0x6e, 0xed, 0xf3, 0xa3, 0xea, 0x71, 0x56, 0x2f, 0xf7, 0x2c,
	0x05, 0xd5, 0x9d, 0xc4, 0x87, 0xb8, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x26, 0x19, 0xe2,
	0x85, 0x04, 0x00, 0x00,
}

func (m *MsgVoteFinalizedRequestPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteFinalizedRequestPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteFinalizedRequestPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PriceFeedResponse != nil {
		{
			size, err := m.PriceFeedResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ValidatedData != nil {
		{
			size, err := m.ValidatedData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TaskRaw != nil {
		{
			size, err := m.TaskRaw.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaskRaw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskRaw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskRaw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.QuorumThresholdPercentage != 0 {
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(m.QuorumThresholdPercentage))
		i--
		dAtA[i] = 0x50
	}
	if len(m.QuorumNumbers) > 0 {
		i -= len(m.QuorumNumbers)
		copy(dAtA[i:], m.QuorumNumbers)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.QuorumNumbers)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TaskCreatedBlock != 0 {
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(m.TaskCreatedBlock))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CallbackFunctionId) > 0 {
		i -= len(m.CallbackFunctionId)
		copy(dAtA[i:], m.CallbackFunctionId)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.CallbackFunctionId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CallbackAddress) > 0 {
		i -= len(m.CallbackAddress)
		copy(dAtA[i:], m.CallbackAddress)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.CallbackAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequestData) > 0 {
		i -= len(m.RequestData)
		copy(dAtA[i:], m.RequestData)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.RequestData)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.Payment.Size()
		i -= size
		if _, err := m.Payment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.FeeToken) > 0 {
		i -= len(m.FeeToken)
		copy(dAtA[i:], m.FeeToken)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.FeeToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskIndex != 0 {
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PriceFeedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceFeedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceFeedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ReferenceTaskIndex != 0 {
		i = encodeVarintVoteFinalizedRequestPrice(dAtA, i, uint64(m.ReferenceTaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteFinalizedRequestPrice(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteFinalizedRequestPrice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgVoteFinalizedRequestPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskRaw != nil {
		l = m.TaskRaw.Size()
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	if m.ValidatedData != nil {
		l = m.ValidatedData.Size()
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	if m.PriceFeedResponse != nil {
		l = m.PriceFeedResponse.Size()
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	return n
}

func (m *TaskRaw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovVoteFinalizedRequestPrice(uint64(m.TaskIndex))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	l = len(m.FeeToken)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	l = m.Payment.Size()
	n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	l = len(m.RequestData)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	l = len(m.CallbackAddress)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	l = len(m.CallbackFunctionId)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	if m.TaskCreatedBlock != 0 {
		n += 1 + sovVoteFinalizedRequestPrice(uint64(m.TaskCreatedBlock))
	}
	l = len(m.QuorumNumbers)
	if l > 0 {
		n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	}
	if m.QuorumThresholdPercentage != 0 {
		n += 1 + sovVoteFinalizedRequestPrice(uint64(m.QuorumThresholdPercentage))
	}
	return n
}

func (m *PriceFeedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReferenceTaskIndex != 0 {
		n += 1 + sovVoteFinalizedRequestPrice(uint64(m.ReferenceTaskIndex))
	}
	l = m.Price.Size()
	n += 1 + l + sovVoteFinalizedRequestPrice(uint64(l))
	return n
}

func sovVoteFinalizedRequestPrice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteFinalizedRequestPrice(x uint64) (n int) {
	return sovVoteFinalizedRequestPrice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgVoteFinalizedRequestPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteFinalizedRequestPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteFinalizedRequestPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteFinalizedRequestPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskRaw", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskRaw == nil {
				m.TaskRaw = &TaskRaw{}
			}
			if err := m.TaskRaw.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidatedData == nil {
				m.ValidatedData = &types.RequestPostRequestValidatedData{}
			}
			if err := m.ValidatedData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceFeedResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PriceFeedResponse == nil {
				m.PriceFeedResponse = &PriceFeedResponse{}
			}
			if err := m.PriceFeedResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteFinalizedRequestPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskRaw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteFinalizedRequestPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskRaw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskRaw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = append(m.RequestId[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestId == nil {
				m.RequestId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestData = append(m.RequestData[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestData == nil {
				m.RequestData = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackFunctionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackFunctionId = append(m.CallbackFunctionId[:0], dAtA[iNdEx:postIndex]...)
			if m.CallbackFunctionId == nil {
				m.CallbackFunctionId = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskCreatedBlock", wireType)
			}
			m.TaskCreatedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskCreatedBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumNumbers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuorumNumbers = append(m.QuorumNumbers[:0], dAtA[iNdEx:postIndex]...)
			if m.QuorumNumbers == nil {
				m.QuorumNumbers = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumThresholdPercentage", wireType)
			}
			m.QuorumThresholdPercentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuorumThresholdPercentage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoteFinalizedRequestPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PriceFeedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteFinalizedRequestPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceFeedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceFeedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceTaskIndex", wireType)
			}
			m.ReferenceTaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferenceTaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteFinalizedRequestPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteFinalizedRequestPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteFinalizedRequestPrice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteFinalizedRequestPrice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteFinalizedRequestPrice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteFinalizedRequestPrice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteFinalizedRequestPrice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteFinalizedRequestPrice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteFinalizedRequestPrice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteFinalizedRequestPrice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteFinalizedRequestPrice = fmt.Errorf("proto: unexpected end of group")
)
