name: intellix

services:
  hardhat:
    image: hardhat:${CONTRACT_VERSION:-v0.4.3}
    environment:
      - LOCALHOST_URL=http://eth:8545
      - ETH_RPC_URL=http://eth:8545
    depends_on:
      eth:
        condition: service_started
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/contracts_deployed_completed" ]
      start_period: 50s
      retries: 3
      interval: 10s

  eth:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "${ETH_HOST_PORT-5006}:${CONTAINER_PORT:-8545}"
    entrypoint: [ "anvil", "--host", "0.0.0.0", "--chain-id", "1337", "--state", "/tmp/anvil.state.json" ]
    platform: ${PLATFORM:-linux/amd64}
    healthcheck:
      test: [ "CMD", "cast", "block-number" ]
      retries: 3
      interval: 10s

  emulator:
    image: intellixlabs-intellix-pelldvs:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
    depends_on:
      hardhat:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/init_emulator.sh" ]
    volumes:
      - ./pelldvs/scripts:/root/scripts
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/emulator_initialized" ]
      start_period: 50s
      retries: 3
      interval: 10s

  dvs:
    image: intellixlabs-intellix-pelldvs:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
    depends_on:
      emulator:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_dvs.sh" ]
    ports:
      - "26653:26653"
    volumes:
      - ./pelldvs/scripts:/root/scripts

  dispatcher:
    image: intellixlabs-intellix-operator:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - DEBUG_ENABLED=${DISPATCHER_DEBUG_ENABLED:-false}
    depends_on:
      gateway:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_dispatcher.sh" ]
    ports:
      - "3345:${DEBUG_PORT:-2345}"
    volumes:
      - ./operator/scripts:/root/scripts

  abci:
    image: intellixlabs-intellix-operator:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
    depends_on:
      gateway:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_abci.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts

  operator:
    image: intellixlabs-intellix-operator:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - GATEWAY_ADDR=${GATEWAY_ADDR:-gateway:8949}
      - DEBUG_ENABLED=${OPERATOR_DEBUG_ENABLED:-false}
    ports:
      - "3346:${DEBUG_PORT:-2345}"
    depends_on:
      gateway:
        condition: service_started
      abci:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_operator.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts

  gateway:
    image: intellixlabs-intellix-operator:latest
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - DEBUG_ENABLED=${GATEWAY_DEBUG_ENABLED:-false}
    entrypoint: [ "bash", "/root/scripts/start_gateway.sh" ]
    ports:
      - "3347:${DEBUG_PORT:-2345}"
    volumes:
      - ./operator/scripts:/root/scripts

  test:
    image: intellixlabs-intellix-operator:latest
    tty: true
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - TIMEOUT_FOR_TASK_PROCESS=${TIMEOUT_FOR_TASK_PROCESS:-30}
    depends_on:
      operator:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/test_wasm.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts
