name: intellix-e2e

services:
  hardhat:
    build:
      context: ./
      dockerfile: ./contracts/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - CONTRACT_VERSION=${CONTRACT_VERSION:-v0.4.8}
      tags:
        - pellnetwork/intellix-e2e-hardhat:${CONTRACT_VERSION:-v0.4.8}
      secrets:
        - github_token

  pelldvs:
    build:
      context: ./
      dockerfile: ./pelldvs/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - PELLDVS_VERSION=${PELLDVS_VERSION:-v0.2.2}
        - EMULATOR_VERSION=${EMULATOR_VERSION:-v0.1.5}
      secrets:
        - github_token

  operator:
    build:
      context: ../
      dockerfile: ./docker/operator/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - PELLDVS_VERSION=${PELLDVS_VERSION:-v0.2.2}
        - DEBUG_ENABLED=${DEBUG_ENABLED:-false}
      secrets:
        - github_token

secrets:
  github_token:
    environment: GITHUB_TOKEN
