// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: intellix/price/dvs_post_process.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DvsPostProcessRequest_PostProcessRequestPriceFeed_FullMethodName = "/intellix.price.DvsPostProcessRequest/PostProcessRequestPriceFeed"
)

// DvsPostProcessRequestClient is the client API for DvsPostProcessRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DvsPostProcessRequestClient interface {
	// PostProcessRequestPriceFeed defines avsi logic processing
	PostProcessRequestPriceFeed(ctx context.Context, in *ProcessRequestPriceFeedIn, opts ...grpc.CallOption) (*PostProcessRequestPriceFeedOut, error)
}

type dvsPostProcessRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewDvsPostProcessRequestClient(cc grpc.ClientConnInterface) DvsPostProcessRequestClient {
	return &dvsPostProcessRequestClient{cc}
}

func (c *dvsPostProcessRequestClient) PostProcessRequestPriceFeed(ctx context.Context, in *ProcessRequestPriceFeedIn, opts ...grpc.CallOption) (*PostProcessRequestPriceFeedOut, error) {
	out := new(PostProcessRequestPriceFeedOut)
	err := c.cc.Invoke(ctx, DvsPostProcessRequest_PostProcessRequestPriceFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DvsPostProcessRequestServer is the server API for DvsPostProcessRequest service.
// All implementations should embed UnimplementedDvsPostProcessRequestServer
// for forward compatibility
type DvsPostProcessRequestServer interface {
	// PostProcessRequestPriceFeed defines avsi logic processing
	PostProcessRequestPriceFeed(context.Context, *ProcessRequestPriceFeedIn) (*PostProcessRequestPriceFeedOut, error)
}

// UnimplementedDvsPostProcessRequestServer should be embedded to have forward compatible implementations.
type UnimplementedDvsPostProcessRequestServer struct {
}

func (UnimplementedDvsPostProcessRequestServer) PostProcessRequestPriceFeed(context.Context, *ProcessRequestPriceFeedIn) (*PostProcessRequestPriceFeedOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostProcessRequestPriceFeed not implemented")
}

// UnsafeDvsPostProcessRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DvsPostProcessRequestServer will
// result in compilation errors.
type UnsafeDvsPostProcessRequestServer interface {
	mustEmbedUnimplementedDvsPostProcessRequestServer()
}

func RegisterDvsPostProcessRequestServer(s grpc.ServiceRegistrar, srv DvsPostProcessRequestServer) {
	s.RegisterService(&DvsPostProcessRequest_ServiceDesc, srv)
}

func _DvsPostProcessRequest_PostProcessRequestPriceFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequestPriceFeedIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DvsPostProcessRequestServer).PostProcessRequestPriceFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DvsPostProcessRequest_PostProcessRequestPriceFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DvsPostProcessRequestServer).PostProcessRequestPriceFeed(ctx, req.(*ProcessRequestPriceFeedIn))
	}
	return interceptor(ctx, in, info, handler)
}

// DvsPostProcessRequest_ServiceDesc is the grpc.ServiceDesc for DvsPostProcessRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DvsPostProcessRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intellix.price.DvsPostProcessRequest",
	HandlerType: (*DvsPostProcessRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostProcessRequestPriceFeed",
			Handler:    _DvsPostProcessRequest_PostProcessRequestPriceFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intellix/price/dvs_post_process.proto",
}
