// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package types

import (
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_ProcessRequestPriceFeedIn            protoreflect.MessageDescriptor
	fd_ProcessRequestPriceFeedIn_task       protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedIn_price_feed protoreflect.FieldDescriptor
)

func init() {
	file_intellix_price_dvs_process_request_proto_init()
	md_ProcessRequestPriceFeedIn = File_intellix_price_dvs_process_request_proto.Messages().ByName("ProcessRequestPriceFeedIn")
	fd_ProcessRequestPriceFeedIn_task = md_ProcessRequestPriceFeedIn.Fields().ByName("task")
	fd_ProcessRequestPriceFeedIn_price_feed = md_ProcessRequestPriceFeedIn.Fields().ByName("price_feed")
}

var _ protoreflect.Message = (*fastReflection_ProcessRequestPriceFeedIn)(nil)

type fastReflection_ProcessRequestPriceFeedIn ProcessRequestPriceFeedIn

func (x *ProcessRequestPriceFeedIn) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ProcessRequestPriceFeedIn)(x)
}

func (x *ProcessRequestPriceFeedIn) slowProtoReflect() protoreflect.Message {
	mi := &file_intellix_price_dvs_process_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ProcessRequestPriceFeedIn_messageType fastReflection_ProcessRequestPriceFeedIn_messageType
var _ protoreflect.MessageType = fastReflection_ProcessRequestPriceFeedIn_messageType{}

type fastReflection_ProcessRequestPriceFeedIn_messageType struct{}

func (x fastReflection_ProcessRequestPriceFeedIn_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ProcessRequestPriceFeedIn)(nil)
}
func (x fastReflection_ProcessRequestPriceFeedIn_messageType) New() protoreflect.Message {
	return new(fastReflection_ProcessRequestPriceFeedIn)
}
func (x fastReflection_ProcessRequestPriceFeedIn_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ProcessRequestPriceFeedIn
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ProcessRequestPriceFeedIn) Descriptor() protoreflect.MessageDescriptor {
	return md_ProcessRequestPriceFeedIn
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ProcessRequestPriceFeedIn) Type() protoreflect.MessageType {
	return _fastReflection_ProcessRequestPriceFeedIn_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ProcessRequestPriceFeedIn) New() protoreflect.Message {
	return new(fastReflection_ProcessRequestPriceFeedIn)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ProcessRequestPriceFeedIn) Interface() protoreflect.ProtoMessage {
	return (*ProcessRequestPriceFeedIn)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ProcessRequestPriceFeedIn) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Task != nil {
		value := protoreflect.ValueOfMessage(x.Task.ProtoReflect())
		if !f(fd_ProcessRequestPriceFeedIn_task, value) {
			return
		}
	}
	if x.PriceFeed != nil {
		value := protoreflect.ValueOfMessage(x.PriceFeed.ProtoReflect())
		if !f(fd_ProcessRequestPriceFeedIn_price_feed, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ProcessRequestPriceFeedIn) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		return x.Task != nil
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		return x.PriceFeed != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedIn) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		x.Task = nil
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		x.PriceFeed = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ProcessRequestPriceFeedIn) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		value := x.Task
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		value := x.PriceFeed
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedIn) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		x.Task = value.Message().Interface().(*TaskRequest)
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		x.PriceFeed = value.Message().Interface().(*PriceFeedParam)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedIn) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		if x.Task == nil {
			x.Task = new(TaskRequest)
		}
		return protoreflect.ValueOfMessage(x.Task.ProtoReflect())
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		if x.PriceFeed == nil {
			x.PriceFeed = new(PriceFeedParam)
		}
		return protoreflect.ValueOfMessage(x.PriceFeed.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ProcessRequestPriceFeedIn) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedIn.task":
		m := new(TaskRequest)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "intellix.price.ProcessRequestPriceFeedIn.price_feed":
		m := new(PriceFeedParam)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedIn"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedIn does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ProcessRequestPriceFeedIn) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in intellix.price.ProcessRequestPriceFeedIn", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ProcessRequestPriceFeedIn) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedIn) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ProcessRequestPriceFeedIn) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ProcessRequestPriceFeedIn) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ProcessRequestPriceFeedIn)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Task != nil {
			l = options.Size(x.Task)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.PriceFeed != nil {
			l = options.Size(x.PriceFeed)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ProcessRequestPriceFeedIn)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.PriceFeed != nil {
			encoded, err := options.Marshal(x.PriceFeed)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if x.Task != nil {
			encoded, err := options.Marshal(x.Task)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ProcessRequestPriceFeedIn)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ProcessRequestPriceFeedIn: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ProcessRequestPriceFeedIn: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Task", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Task == nil {
					x.Task = &TaskRequest{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Task); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PriceFeed", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.PriceFeed == nil {
					x.PriceFeed = &PriceFeedParam{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.PriceFeed); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_ProcessRequestPriceFeedOut                protoreflect.MessageDescriptor
	fd_ProcessRequestPriceFeedOut_request_id     protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_task_index     protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_price          protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_timestamp      protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_source_count   protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_operator_count protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_block_height   protoreflect.FieldDescriptor
	fd_ProcessRequestPriceFeedOut_block_range    protoreflect.FieldDescriptor
)

func init() {
	file_intellix_price_dvs_process_request_proto_init()
	md_ProcessRequestPriceFeedOut = File_intellix_price_dvs_process_request_proto.Messages().ByName("ProcessRequestPriceFeedOut")
	fd_ProcessRequestPriceFeedOut_request_id = md_ProcessRequestPriceFeedOut.Fields().ByName("request_id")
	fd_ProcessRequestPriceFeedOut_task_index = md_ProcessRequestPriceFeedOut.Fields().ByName("task_index")
	fd_ProcessRequestPriceFeedOut_price = md_ProcessRequestPriceFeedOut.Fields().ByName("price")
	fd_ProcessRequestPriceFeedOut_timestamp = md_ProcessRequestPriceFeedOut.Fields().ByName("timestamp")
	fd_ProcessRequestPriceFeedOut_source_count = md_ProcessRequestPriceFeedOut.Fields().ByName("source_count")
	fd_ProcessRequestPriceFeedOut_operator_count = md_ProcessRequestPriceFeedOut.Fields().ByName("operator_count")
	fd_ProcessRequestPriceFeedOut_block_height = md_ProcessRequestPriceFeedOut.Fields().ByName("block_height")
	fd_ProcessRequestPriceFeedOut_block_range = md_ProcessRequestPriceFeedOut.Fields().ByName("block_range")
}

var _ protoreflect.Message = (*fastReflection_ProcessRequestPriceFeedOut)(nil)

type fastReflection_ProcessRequestPriceFeedOut ProcessRequestPriceFeedOut

func (x *ProcessRequestPriceFeedOut) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ProcessRequestPriceFeedOut)(x)
}

func (x *ProcessRequestPriceFeedOut) slowProtoReflect() protoreflect.Message {
	mi := &file_intellix_price_dvs_process_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ProcessRequestPriceFeedOut_messageType fastReflection_ProcessRequestPriceFeedOut_messageType
var _ protoreflect.MessageType = fastReflection_ProcessRequestPriceFeedOut_messageType{}

type fastReflection_ProcessRequestPriceFeedOut_messageType struct{}

func (x fastReflection_ProcessRequestPriceFeedOut_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ProcessRequestPriceFeedOut)(nil)
}
func (x fastReflection_ProcessRequestPriceFeedOut_messageType) New() protoreflect.Message {
	return new(fastReflection_ProcessRequestPriceFeedOut)
}
func (x fastReflection_ProcessRequestPriceFeedOut_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ProcessRequestPriceFeedOut
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ProcessRequestPriceFeedOut) Descriptor() protoreflect.MessageDescriptor {
	return md_ProcessRequestPriceFeedOut
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ProcessRequestPriceFeedOut) Type() protoreflect.MessageType {
	return _fastReflection_ProcessRequestPriceFeedOut_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ProcessRequestPriceFeedOut) New() protoreflect.Message {
	return new(fastReflection_ProcessRequestPriceFeedOut)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ProcessRequestPriceFeedOut) Interface() protoreflect.ProtoMessage {
	return (*ProcessRequestPriceFeedOut)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ProcessRequestPriceFeedOut) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.RequestId) != 0 {
		value := protoreflect.ValueOfBytes(x.RequestId)
		if !f(fd_ProcessRequestPriceFeedOut_request_id, value) {
			return
		}
	}
	if x.TaskIndex != uint32(0) {
		value := protoreflect.ValueOfUint32(x.TaskIndex)
		if !f(fd_ProcessRequestPriceFeedOut_task_index, value) {
			return
		}
	}
	if x.Price != "" {
		value := protoreflect.ValueOfString(x.Price)
		if !f(fd_ProcessRequestPriceFeedOut_price, value) {
			return
		}
	}
	if x.Timestamp != int64(0) {
		value := protoreflect.ValueOfInt64(x.Timestamp)
		if !f(fd_ProcessRequestPriceFeedOut_timestamp, value) {
			return
		}
	}
	if x.SourceCount != int32(0) {
		value := protoreflect.ValueOfInt32(x.SourceCount)
		if !f(fd_ProcessRequestPriceFeedOut_source_count, value) {
			return
		}
	}
	if x.OperatorCount != int32(0) {
		value := protoreflect.ValueOfInt32(x.OperatorCount)
		if !f(fd_ProcessRequestPriceFeedOut_operator_count, value) {
			return
		}
	}
	if x.BlockHeight != uint64(0) {
		value := protoreflect.ValueOfUint64(x.BlockHeight)
		if !f(fd_ProcessRequestPriceFeedOut_block_height, value) {
			return
		}
	}
	if x.BlockRange != nil {
		value := protoreflect.ValueOfMessage(x.BlockRange.ProtoReflect())
		if !f(fd_ProcessRequestPriceFeedOut_block_range, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ProcessRequestPriceFeedOut) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		return len(x.RequestId) != 0
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		return x.TaskIndex != uint32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		return x.Price != ""
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		return x.Timestamp != int64(0)
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		return x.SourceCount != int32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		return x.OperatorCount != int32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		return x.BlockHeight != uint64(0)
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		return x.BlockRange != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedOut) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		x.RequestId = nil
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		x.TaskIndex = uint32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		x.Price = ""
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		x.Timestamp = int64(0)
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		x.SourceCount = int32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		x.OperatorCount = int32(0)
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		x.BlockHeight = uint64(0)
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		x.BlockRange = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ProcessRequestPriceFeedOut) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		value := x.RequestId
		return protoreflect.ValueOfBytes(value)
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		value := x.TaskIndex
		return protoreflect.ValueOfUint32(value)
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		value := x.Price
		return protoreflect.ValueOfString(value)
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		value := x.Timestamp
		return protoreflect.ValueOfInt64(value)
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		value := x.SourceCount
		return protoreflect.ValueOfInt32(value)
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		value := x.OperatorCount
		return protoreflect.ValueOfInt32(value)
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		value := x.BlockHeight
		return protoreflect.ValueOfUint64(value)
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		value := x.BlockRange
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedOut) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		x.RequestId = value.Bytes()
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		x.TaskIndex = uint32(value.Uint())
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		x.Price = value.Interface().(string)
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		x.Timestamp = value.Int()
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		x.SourceCount = int32(value.Int())
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		x.OperatorCount = int32(value.Int())
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		x.BlockHeight = value.Uint()
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		x.BlockRange = value.Message().Interface().(*BlockRange)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedOut) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		if x.BlockRange == nil {
			x.BlockRange = new(BlockRange)
		}
		return protoreflect.ValueOfMessage(x.BlockRange.ProtoReflect())
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		panic(fmt.Errorf("field request_id of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		panic(fmt.Errorf("field task_index of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		panic(fmt.Errorf("field price of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		panic(fmt.Errorf("field timestamp of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		panic(fmt.Errorf("field source_count of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		panic(fmt.Errorf("field operator_count of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		panic(fmt.Errorf("field block_height of message intellix.price.ProcessRequestPriceFeedOut is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ProcessRequestPriceFeedOut) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.ProcessRequestPriceFeedOut.request_id":
		return protoreflect.ValueOfBytes(nil)
	case "intellix.price.ProcessRequestPriceFeedOut.task_index":
		return protoreflect.ValueOfUint32(uint32(0))
	case "intellix.price.ProcessRequestPriceFeedOut.price":
		return protoreflect.ValueOfString("")
	case "intellix.price.ProcessRequestPriceFeedOut.timestamp":
		return protoreflect.ValueOfInt64(int64(0))
	case "intellix.price.ProcessRequestPriceFeedOut.source_count":
		return protoreflect.ValueOfInt32(int32(0))
	case "intellix.price.ProcessRequestPriceFeedOut.operator_count":
		return protoreflect.ValueOfInt32(int32(0))
	case "intellix.price.ProcessRequestPriceFeedOut.block_height":
		return protoreflect.ValueOfUint64(uint64(0))
	case "intellix.price.ProcessRequestPriceFeedOut.block_range":
		m := new(BlockRange)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.ProcessRequestPriceFeedOut"))
		}
		panic(fmt.Errorf("message intellix.price.ProcessRequestPriceFeedOut does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ProcessRequestPriceFeedOut) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in intellix.price.ProcessRequestPriceFeedOut", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ProcessRequestPriceFeedOut) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ProcessRequestPriceFeedOut) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ProcessRequestPriceFeedOut) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ProcessRequestPriceFeedOut) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ProcessRequestPriceFeedOut)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.RequestId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TaskIndex != 0 {
			n += 1 + runtime.Sov(uint64(x.TaskIndex))
		}
		l = len(x.Price)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Timestamp != 0 {
			n += 1 + runtime.Sov(uint64(x.Timestamp))
		}
		if x.SourceCount != 0 {
			n += 1 + runtime.Sov(uint64(x.SourceCount))
		}
		if x.OperatorCount != 0 {
			n += 1 + runtime.Sov(uint64(x.OperatorCount))
		}
		if x.BlockHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.BlockHeight))
		}
		if x.BlockRange != nil {
			l = options.Size(x.BlockRange)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ProcessRequestPriceFeedOut)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.BlockRange != nil {
			encoded, err := options.Marshal(x.BlockRange)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x42
		}
		if x.BlockHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BlockHeight))
			i--
			dAtA[i] = 0x38
		}
		if x.OperatorCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.OperatorCount))
			i--
			dAtA[i] = 0x30
		}
		if x.SourceCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SourceCount))
			i--
			dAtA[i] = 0x28
		}
		if x.Timestamp != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Timestamp))
			i--
			dAtA[i] = 0x20
		}
		if len(x.Price) > 0 {
			i -= len(x.Price)
			copy(dAtA[i:], x.Price)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Price)))
			i--
			dAtA[i] = 0x1a
		}
		if x.TaskIndex != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TaskIndex))
			i--
			dAtA[i] = 0x10
		}
		if len(x.RequestId) > 0 {
			i -= len(x.RequestId)
			copy(dAtA[i:], x.RequestId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RequestId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ProcessRequestPriceFeedOut)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ProcessRequestPriceFeedOut: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ProcessRequestPriceFeedOut: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RequestId = append(x.RequestId[:0], dAtA[iNdEx:postIndex]...)
				if x.RequestId == nil {
					x.RequestId = []byte{}
				}
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
				}
				x.TaskIndex = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TaskIndex |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Price = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
				}
				x.Timestamp = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Timestamp |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SourceCount", wireType)
				}
				x.SourceCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SourceCount |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OperatorCount", wireType)
				}
				x.OperatorCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.OperatorCount |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
				}
				x.BlockHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BlockHeight |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BlockRange", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.BlockRange == nil {
					x.BlockRange = &BlockRange{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.BlockRange); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_BlockRange       protoreflect.MessageDescriptor
	fd_BlockRange_start protoreflect.FieldDescriptor
	fd_BlockRange_end   protoreflect.FieldDescriptor
)

func init() {
	file_intellix_price_dvs_process_request_proto_init()
	md_BlockRange = File_intellix_price_dvs_process_request_proto.Messages().ByName("BlockRange")
	fd_BlockRange_start = md_BlockRange.Fields().ByName("start")
	fd_BlockRange_end = md_BlockRange.Fields().ByName("end")
}

var _ protoreflect.Message = (*fastReflection_BlockRange)(nil)

type fastReflection_BlockRange BlockRange

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	return (*fastReflection_BlockRange)(x)
}

func (x *BlockRange) slowProtoReflect() protoreflect.Message {
	mi := &file_intellix_price_dvs_process_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_BlockRange_messageType fastReflection_BlockRange_messageType
var _ protoreflect.MessageType = fastReflection_BlockRange_messageType{}

type fastReflection_BlockRange_messageType struct{}

func (x fastReflection_BlockRange_messageType) Zero() protoreflect.Message {
	return (*fastReflection_BlockRange)(nil)
}
func (x fastReflection_BlockRange_messageType) New() protoreflect.Message {
	return new(fastReflection_BlockRange)
}
func (x fastReflection_BlockRange_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_BlockRange
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_BlockRange) Descriptor() protoreflect.MessageDescriptor {
	return md_BlockRange
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_BlockRange) Type() protoreflect.MessageType {
	return _fastReflection_BlockRange_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_BlockRange) New() protoreflect.Message {
	return new(fastReflection_BlockRange)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_BlockRange) Interface() protoreflect.ProtoMessage {
	return (*BlockRange)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_BlockRange) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Start != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Start)
		if !f(fd_BlockRange_start, value) {
			return
		}
	}
	if x.End != uint64(0) {
		value := protoreflect.ValueOfUint64(x.End)
		if !f(fd_BlockRange_end, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_BlockRange) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "intellix.price.BlockRange.start":
		return x.Start != uint64(0)
	case "intellix.price.BlockRange.end":
		return x.End != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BlockRange) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "intellix.price.BlockRange.start":
		x.Start = uint64(0)
	case "intellix.price.BlockRange.end":
		x.End = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_BlockRange) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "intellix.price.BlockRange.start":
		value := x.Start
		return protoreflect.ValueOfUint64(value)
	case "intellix.price.BlockRange.end":
		value := x.End
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BlockRange) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "intellix.price.BlockRange.start":
		x.Start = value.Uint()
	case "intellix.price.BlockRange.end":
		x.End = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BlockRange) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.BlockRange.start":
		panic(fmt.Errorf("field start of message intellix.price.BlockRange is not mutable"))
	case "intellix.price.BlockRange.end":
		panic(fmt.Errorf("field end of message intellix.price.BlockRange is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_BlockRange) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "intellix.price.BlockRange.start":
		return protoreflect.ValueOfUint64(uint64(0))
	case "intellix.price.BlockRange.end":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: intellix.price.BlockRange"))
		}
		panic(fmt.Errorf("message intellix.price.BlockRange does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_BlockRange) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in intellix.price.BlockRange", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_BlockRange) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BlockRange) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_BlockRange) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_BlockRange) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*BlockRange)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Start != 0 {
			n += 1 + runtime.Sov(uint64(x.Start))
		}
		if x.End != 0 {
			n += 1 + runtime.Sov(uint64(x.End))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*BlockRange)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.End != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.End))
			i--
			dAtA[i] = 0x10
		}
		if x.Start != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Start))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*BlockRange)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: BlockRange: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: BlockRange: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
				}
				x.Start = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Start |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
				}
				x.End = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.End |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: intellix/price/dvs_process_request.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessRequestPriceFeedIn defines task request from task-dispatcher
type ProcessRequestPriceFeedIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task      *TaskRequest    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	PriceFeed *PriceFeedParam `protobuf:"bytes,2,opt,name=price_feed,json=priceFeed,proto3" json:"price_feed,omitempty"`
}

func (x *ProcessRequestPriceFeedIn) Reset() {
	*x = ProcessRequestPriceFeedIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intellix_price_dvs_process_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessRequestPriceFeedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestPriceFeedIn) ProtoMessage() {}

// Deprecated: Use ProcessRequestPriceFeedIn.ProtoReflect.Descriptor instead.
func (*ProcessRequestPriceFeedIn) Descriptor() ([]byte, []int) {
	return file_intellix_price_dvs_process_request_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequestPriceFeedIn) GetTask() *TaskRequest {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ProcessRequestPriceFeedIn) GetPriceFeed() *PriceFeedParam {
	if x != nil {
		return x.PriceFeed
	}
	return nil
}

// ProcessRequestPriceFeedOut
type ProcessRequestPriceFeedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId []byte `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TaskIndex uint32 `protobuf:"varint,2,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	// Aggregated final price
	Price string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Timestamp when aggregation was completed
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of data sources participated in aggregation
	SourceCount int32 `protobuf:"varint,5,opt,name=source_count,json=sourceCount,proto3" json:"source_count,omitempty"`
	// Number of operators participated in aggregation
	OperatorCount int32 `protobuf:"varint,6,opt,name=operator_count,json=operatorCount,proto3" json:"operator_count,omitempty"`
	// Block height at which aggregation was completed
	BlockHeight uint64 `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Block range used for aggregation
	BlockRange *BlockRange `protobuf:"bytes,8,opt,name=block_range,json=blockRange,proto3" json:"block_range,omitempty"`
}

func (x *ProcessRequestPriceFeedOut) Reset() {
	*x = ProcessRequestPriceFeedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intellix_price_dvs_process_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessRequestPriceFeedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestPriceFeedOut) ProtoMessage() {}

// Deprecated: Use ProcessRequestPriceFeedOut.ProtoReflect.Descriptor instead.
func (*ProcessRequestPriceFeedOut) Descriptor() ([]byte, []int) {
	return file_intellix_price_dvs_process_request_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessRequestPriceFeedOut) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ProcessRequestPriceFeedOut) GetTaskIndex() uint32 {
	if x != nil {
		return x.TaskIndex
	}
	return 0
}

func (x *ProcessRequestPriceFeedOut) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ProcessRequestPriceFeedOut) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessRequestPriceFeedOut) GetSourceCount() int32 {
	if x != nil {
		return x.SourceCount
	}
	return 0
}

func (x *ProcessRequestPriceFeedOut) GetOperatorCount() int32 {
	if x != nil {
		return x.OperatorCount
	}
	return 0
}

func (x *ProcessRequestPriceFeedOut) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *ProcessRequestPriceFeedOut) GetBlockRange() *BlockRange {
	if x != nil {
		return x.BlockRange
	}
	return nil
}

// BlockRange defines the range of blocks used for price aggregation
type BlockRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Start block height for aggregation
	Start uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// End block height for aggregation
	End uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intellix_price_dvs_process_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_intellix_price_dvs_process_request_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BlockRange) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_intellix_price_dvs_process_request_proto protoreflect.FileDescriptor

var file_intellix_price_dvs_process_request_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x2f, 0x64, 0x76, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x6e, 0x74, 0x65,
	0x6c, 0x6c, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69,
	0x78, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x49, 0x6e,
	0x12, 0x2f, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78,
	0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x3a, 0x47, 0xca, 0xb4, 0x2d, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x8a, 0xe7, 0xb0,
	0x2a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78, 0x2f, 0x78, 0x2f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x2f, 0x64, 0x76, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x22, 0xfa, 0x02, 0x0a, 0x1a, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x39, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x23, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68,
	0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3b, 0x0a, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x3a, 0x1b, 0xca, 0xb4, 0x2d, 0x17, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x34, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x32, 0x87, 0x01, 0x0a,
	0x11, 0x44, 0x76, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x72, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x29, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x1a, 0x2a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x78, 0x2f, 0x78, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_intellix_price_dvs_process_request_proto_rawDescOnce sync.Once
	file_intellix_price_dvs_process_request_proto_rawDescData = file_intellix_price_dvs_process_request_proto_rawDesc
)

func file_intellix_price_dvs_process_request_proto_rawDescGZIP() []byte {
	file_intellix_price_dvs_process_request_proto_rawDescOnce.Do(func() {
		file_intellix_price_dvs_process_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_intellix_price_dvs_process_request_proto_rawDescData)
	})
	return file_intellix_price_dvs_process_request_proto_rawDescData
}

var file_intellix_price_dvs_process_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_intellix_price_dvs_process_request_proto_goTypes = []interface{}{
	(*ProcessRequestPriceFeedIn)(nil),  // 0: intellix.price.ProcessRequestPriceFeedIn
	(*ProcessRequestPriceFeedOut)(nil), // 1: intellix.price.ProcessRequestPriceFeedOut
	(*BlockRange)(nil),                 // 2: intellix.price.BlockRange
	(*TaskRequest)(nil),                // 3: intellix.price.TaskRequest
	(*PriceFeedParam)(nil),             // 4: intellix.price.PriceFeedParam
}
var file_intellix_price_dvs_process_request_proto_depIdxs = []int32{
	3, // 0: intellix.price.ProcessRequestPriceFeedIn.task:type_name -> intellix.price.TaskRequest
	4, // 1: intellix.price.ProcessRequestPriceFeedIn.price_feed:type_name -> intellix.price.PriceFeedParam
	2, // 2: intellix.price.ProcessRequestPriceFeedOut.block_range:type_name -> intellix.price.BlockRange
	0, // 3: intellix.price.DvsProcessRequest.ProcessRequestPriceFeed:input_type -> intellix.price.ProcessRequestPriceFeedIn
	1, // 4: intellix.price.DvsProcessRequest.ProcessRequestPriceFeed:output_type -> intellix.price.ProcessRequestPriceFeedOut
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_intellix_price_dvs_process_request_proto_init() }
func file_intellix_price_dvs_process_request_proto_init() {
	if File_intellix_price_dvs_process_request_proto != nil {
		return
	}
	file_intellix_price_task_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_intellix_price_dvs_process_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessRequestPriceFeedIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intellix_price_dvs_process_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessRequestPriceFeedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intellix_price_dvs_process_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_intellix_price_dvs_process_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intellix_price_dvs_process_request_proto_goTypes,
		DependencyIndexes: file_intellix_price_dvs_process_request_proto_depIdxs,
		MessageInfos:      file_intellix_price_dvs_process_request_proto_msgTypes,
	}.Build()
	File_intellix_price_dvs_process_request_proto = out.File
	file_intellix_price_dvs_process_request_proto_rawDesc = nil
	file_intellix_price_dvs_process_request_proto_goTypes = nil
	file_intellix_price_dvs_process_request_proto_depIdxs = nil
}
