name: intellix

services:

  abci:
    image: intellix-testnet-operator:latest
    environment:
      - ETH_RPC_URL=${SERVICE_CHAIN_RPC_URL}
      - ETH_WS_URL=${SERVICE_CHAIN_WS_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - VALIDATOR_KEY_MNEMONIC=${VALIDATOR_KEY_MNEMONIC}
      - OPERATOR_KEY_MNEMONIC=${OPERATOR_KEY_MNEMONIC}
    entrypoint: [ "bash", "/root/scripts/start_abci.sh" ]
    volumes:
      - ${HOST_INTELLIX_HOME:-./.intellix}:/root/.intellix
      - ./operator:/root/scripts
    ports:
      - "${HOST_ABCI_PORT:-26657}:26657"

networks:
  default:
    external: true
    name: intellix-devnet
