name: intellix

services:
  dispatcher:
    image: intellix-testnet-operator:latest
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SERVICE_CHAIN_WS_URL=${SERVICE_CHAIN_WS_URL}
      - NETWORK=${NETWORK}
      - CHAIN_ID=${CHAIN_ID}
    entrypoint: [ "bash", "/root/scripts/start_dispatcher.sh" ]
    ports:
      - "${HOST_DEBUG_PORT:-23345}:${DEBUG_PORT:-2345}"
    volumes:
      - "${HOST_PELLDVS_HOME:-./.dispatcher}:/root/.pelldvs"
      - ./operator:/root/scripts

  operator:
    image: intellix-testnet-operator:latest
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - GATEWAY_ADDR=${GATEWAY_ADDR:-gateway:8949}
      - OPERATOR_KEY=${OPERATOR_KEY}
      - OPERATOR_KEY_MNEMONIC=${OPERATOR_KEY_MNEMONIC}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REGISTRY_ROUTER_ADDRESS=${REGISTRY_ROUTER_ADDRESS}
    ports:
      - "${HOST_DEBUG_PORT:-23346}:${DEBUG_PORT:-2345}"
      - "${HOST_SERVER_PORT:-36657}:26657"
    entrypoint: [ "bash", "/root/scripts/start_operator.sh" ]
    volumes:
      - "${HOST_PELLDVS_HOME:-./.operator}:/root/.pelldvs"
      - ./operator:/root/scripts

networks:
  default:
    external: true
    name: intellix-devnet
