syntax = "proto3";
package intellix.price;

import "gogoproto/gogo.proto";
import "intellix/price/task.proto";
import "intellix/pelldvs/dvs_post_process_validated.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "intellix/x/price/types";

service DvsPostProcessRequest {
  // PostProcessRequestPriceFeed defines avsi logic processing
  rpc PostProcessRequestPriceFeed(pelldvs.RequestPostRequestValidatedData) returns (ResponsePostRequestPriceFeed) {}
}

message ResponsePostRequestPriceFeed {
}