syntax = "proto3";
package intellix.price;

import "gogoproto/gogo.proto";
import "intellix/pelldvs/dvs_post_process_validated.proto";
import "intellix/price/dvs_request.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "intellix/x/price/types";

service DVSResponse {
  // PostProcessRequestPriceFeed defines avsi logic processing
  rpc ResponsePriceFeed(RequestPriceFeedIn) returns (ResponsePriceFeedOut) {}
}

message ResponsePriceFeedOut {
}