syntax = "proto3";
package intellix.price;

import "gogoproto/gogo.proto";
import "intellix/price/task.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "intellix/x/price/types";

service DvsProcessRequest {
  // ProcessRequestPriceFeed defines avsi logic processing
  rpc ProcessRequestPriceFeed(ProcessPriceFeedMsg) returns (ProcessPriceFeedResp) {}
}

// ProcessPriceFeedMsg defines task request from task-dispatcher
message ProcessPriceFeedMsg {
  option (cosmos_proto.implements_interface) = "cosmos.base.v1beta1.Msg";
  option (amino.name) = "intellix/x/price/dvs/process_price_feed";

  TaskRequestRaw raw = 1;
}

// ProcessPriceFeedResp defines response from data that after processing
message ProcessPriceFeedResp {
  bytes data = 1;
}
