syntax = "proto3";
package intellix.price;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "intellix/price/params.proto";
import "intellix/price/vote_finalized_request_price.proto";
import "intellix/price/vote_request_price_feed.proto";

option go_package = "intellix/x/price/types";

// Msg defines the price module message service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams updates the module parameters via governance.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // VoteRequestPriceFeed submits a price feed vote.
  rpc VoteRequestPriceFeed(MsgVoteRequestPriceFeed)
      returns (MsgVoteRequestPriceFeedResponse);

  // VoteFinalizedRequestPrice submits a finalized price vote.
  rpc VoteFinalizedRequestPrice(MsgVoteFinalizedRequestPrice)
      returns (MsgVoteFinalizedRequestPriceResponse);
}

// MsgUpdateParams represents a request to update module parameters.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "intellix/x/price/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless
  // overwritten).
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];

  // params defines the module parameters to update.
  //
  // NOTE: All parameters must be supplied.
  Params params = 2
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// MsgUpdateParamsResponse represents an empty response for parameter update.
message MsgUpdateParamsResponse {}

// MsgVoteRequestPriceFeedResponse represents an empty response for price feed
// vote.
message MsgVoteRequestPriceFeedResponse {}

// MsgVoteFinalizedRequestPriceResponse represents an empty response for
// finalized price vote.
message MsgVoteFinalizedRequestPriceResponse {}
