syntax = "proto3";
package intellix.price;

import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "intellix/x/price/types";

message MsgVoteRequestPriceFeed {
  option (cosmos_proto.implements_interface) = "cosmos.base.v1beta1.Msg";

  string operator_id = 1;
  bytes request_id = 2;
  string base_symbol = 3;
  string quote_symbol = 4;
  string price = 5 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false
  ];
  int64 timestamp = 6;
  uint64 block_height = 7;
  string date_source = 8;
}