// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intellix/vrf/msg_server.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TaskMetadata struct {
	TaskIndex                uint32 `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	Height                   uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ChainId                  uint64 `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GroupNumbers             []byte `protobuf:"bytes,4,opt,name=group_numbers,json=groupNumbers,proto3" json:"group_numbers,omitempty"`
	GroupThresholdPercentage uint32 `protobuf:"varint,5,opt,name=group_threshold_percentage,json=groupThresholdPercentage,proto3" json:"group_threshold_percentage,omitempty"`
}

func (m *TaskMetadata) Reset()         { *m = TaskMetadata{} }
func (m *TaskMetadata) String() string { return proto.CompactTextString(m) }
func (*TaskMetadata) ProtoMessage()    {}
func (*TaskMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b5b703e76daccbc, []int{0}
}
func (m *TaskMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMetadata.Merge(m, src)
}
func (m *TaskMetadata) XXX_Size() int {
	return m.Size()
}
func (m *TaskMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMetadata proto.InternalMessageInfo

func (m *TaskMetadata) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *TaskMetadata) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TaskMetadata) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TaskMetadata) GetGroupNumbers() []byte {
	if m != nil {
		return m.GroupNumbers
	}
	return nil
}

func (m *TaskMetadata) GetGroupThresholdPercentage() uint32 {
	if m != nil {
		return m.GroupThresholdPercentage
	}
	return 0
}

type VRFData struct {
	VrfValue []byte `protobuf:"bytes,1,opt,name=vrf_value,json=vrfValue,proto3" json:"vrf_value,omitempty"`
	VrfProof []byte `protobuf:"bytes,2,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
}

func (m *VRFData) Reset()         { *m = VRFData{} }
func (m *VRFData) String() string { return proto.CompactTextString(m) }
func (*VRFData) ProtoMessage()    {}
func (*VRFData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b5b703e76daccbc, []int{1}
}
func (m *VRFData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VRFData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VRFData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VRFData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VRFData.Merge(m, src)
}
func (m *VRFData) XXX_Size() int {
	return m.Size()
}
func (m *VRFData) XXX_DiscardUnknown() {
	xxx_messageInfo_VRFData.DiscardUnknown(m)
}

var xxx_messageInfo_VRFData proto.InternalMessageInfo

func (m *VRFData) GetVrfValue() []byte {
	if m != nil {
		return m.VrfValue
	}
	return nil
}

func (m *VRFData) GetVrfProof() []byte {
	if m != nil {
		return m.VrfProof
	}
	return nil
}

type GenerateRandomNumberRequest struct {
	TaskMetadata *TaskMetadata `protobuf:"bytes,1,opt,name=task_metadata,json=taskMetadata,proto3" json:"task_metadata,omitempty"`
	VrfData      []*VRFData    `protobuf:"bytes,2,rep,name=vrf_data,json=vrfData,proto3" json:"vrf_data,omitempty"`
}

func (m *GenerateRandomNumberRequest) Reset()         { *m = GenerateRandomNumberRequest{} }
func (m *GenerateRandomNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRandomNumberRequest) ProtoMessage()    {}
func (*GenerateRandomNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b5b703e76daccbc, []int{2}
}
func (m *GenerateRandomNumberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateRandomNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateRandomNumberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateRandomNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRandomNumberRequest.Merge(m, src)
}
func (m *GenerateRandomNumberRequest) XXX_Size() int {
	return m.Size()
}
func (m *GenerateRandomNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRandomNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRandomNumberRequest proto.InternalMessageInfo

func (m *GenerateRandomNumberRequest) GetTaskMetadata() *TaskMetadata {
	if m != nil {
		return m.TaskMetadata
	}
	return nil
}

func (m *GenerateRandomNumberRequest) GetVrfData() []*VRFData {
	if m != nil {
		return m.VrfData
	}
	return nil
}

type GenerateRandomNumberResponse struct {
	TaskIndex    uint32                  `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	RandomNumber []cosmossdk_io_math.Int `protobuf:"bytes,2,rep,name=randomNumber,proto3,customtype=cosmossdk.io/math.Int" json:"randomNumber"`
}

func (m *GenerateRandomNumberResponse) Reset()         { *m = GenerateRandomNumberResponse{} }
func (m *GenerateRandomNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateRandomNumberResponse) ProtoMessage()    {}
func (*GenerateRandomNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b5b703e76daccbc, []int{3}
}
func (m *GenerateRandomNumberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateRandomNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateRandomNumberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateRandomNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRandomNumberResponse.Merge(m, src)
}
func (m *GenerateRandomNumberResponse) XXX_Size() int {
	return m.Size()
}
func (m *GenerateRandomNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRandomNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRandomNumberResponse proto.InternalMessageInfo

func (m *GenerateRandomNumberResponse) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

type DVSResultResponse struct {
}

func (m *DVSResultResponse) Reset()         { *m = DVSResultResponse{} }
func (m *DVSResultResponse) String() string { return proto.CompactTextString(m) }
func (*DVSResultResponse) ProtoMessage()    {}
func (*DVSResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b5b703e76daccbc, []int{4}
}
func (m *DVSResultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DVSResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DVSResultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DVSResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DVSResultResponse.Merge(m, src)
}
func (m *DVSResultResponse) XXX_Size() int {
	return m.Size()
}
func (m *DVSResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DVSResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DVSResultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TaskMetadata)(nil), "intellix.vrf.TaskMetadata")
	proto.RegisterType((*VRFData)(nil), "intellix.vrf.VRFData")
	proto.RegisterType((*GenerateRandomNumberRequest)(nil), "intellix.vrf.GenerateRandomNumberRequest")
	proto.RegisterType((*GenerateRandomNumberResponse)(nil), "intellix.vrf.GenerateRandomNumberResponse")
	proto.RegisterType((*DVSResultResponse)(nil), "intellix.vrf.DVSResultResponse")
}

func init() { proto.RegisterFile("intellix/vrf/msg_server.proto", fileDescriptor_7b5b703e76daccbc) }

var fileDescriptor_7b5b703e76daccbc = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x4e, 0x14, 0x41,
	0x10, 0xde, 0x01, 0xe4, 0xa7, 0x19, 0x0e, 0x0c, 0x82, 0xcb, 0x02, 0xcb, 0x66, 0xbc, 0xac, 0x24,
	0xce, 0xf0, 0x73, 0x23, 0x26, 0x46, 0x24, 0x28, 0x07, 0x0c, 0x69, 0xc8, 0x1e, 0xbc, 0x4c, 0x7a,
	0x99, 0x9a, 0x9f, 0x30, 0x33, 0x3d, 0x74, 0xf7, 0x8c, 0xf8, 0x0a, 0x9e, 0x7c, 0x01, 0xdf, 0xc1,
	0x83, 0x6f, 0x60, 0x4c, 0x88, 0x27, 0x8e, 0xc6, 0x03, 0x31, 0xec, 0xc1, 0xc4, 0xa7, 0x30, 0xdd,
	0x3d, 0x4b, 0x76, 0x23, 0x41, 0xbd, 0xec, 0x76, 0xd5, 0x57, 0xdf, 0xd4, 0x57, 0xf5, 0xa5, 0x1b,
	0xad, 0xc4, 0x99, 0x80, 0x24, 0x89, 0xcf, 0xdd, 0x92, 0x05, 0x6e, 0xca, 0x43, 0x8f, 0x03, 0x2b,
	0x81, 0x39, 0x39, 0xa3, 0x82, 0x5a, 0x66, 0x1f, 0x76, 0x4a, 0x16, 0x34, 0xee, 0x87, 0x34, 0xa4,
	0x0a, 0x70, 0xe5, 0x49, 0xd7, 0x34, 0x1e, 0x9c, 0x50, 0x9e, 0x52, 0x2e, 0xc9, 0x6e, 0xb9, 0x21,
	0xff, 0x2a, 0x60, 0x51, 0x03, 0x9e, 0x66, 0xe8, 0xa0, 0x82, 0x66, 0x49, 0x1a, 0x67, 0xd4, 0x55,
	0xbf, 0x3a, 0x65, 0x7f, 0x36, 0x90, 0x79, 0x4c, 0xf8, 0xe9, 0x01, 0x08, 0xe2, 0x13, 0x41, 0xac,
	0x15, 0x84, 0x04, 0xe1, 0xa7, 0x5e, 0x9c, 0xf9, 0x70, 0x5e, 0x37, 0x5a, 0x46, 0x7b, 0x06, 0x4f,
	0xc9, 0xcc, 0xbe, 0x4c, 0x58, 0x0b, 0x68, 0x3c, 0x82, 0x38, 0x8c, 0x44, 0x7d, 0x44, 0x41, 0x55,
	0x64, 0x2d, 0xa2, 0xc9, 0x93, 0x88, 0xc4, 0x99, 0x17, 0xfb, 0xf5, 0xd1, 0x96, 0xd1, 0x1e, 0xc3,
	0x13, 0x2a, 0xde, 0xf7, 0xad, 0x87, 0x68, 0x26, 0x64, 0xb4, 0xc8, 0xbd, 0xac, 0x48, 0xbb, 0xc0,
	0x78, 0x7d, 0xac, 0x65, 0xb4, 0x4d, 0x6c, 0xaa, 0xe4, 0x2b, 0x9d, 0xb3, 0x9e, 0xa0, 0x86, 0x2e,
	0x12, 0x11, 0x03, 0x1e, 0xd1, 0xc4, 0xf7, 0x72, 0x60, 0x27, 0x90, 0x09, 0x12, 0x42, 0xfd, 0x9e,
	0xea, 0x55, 0x57, 0x15, 0xc7, 0xfd, 0x82, 0xc3, 0x1b, 0xdc, 0x7e, 0x8e, 0x26, 0x3a, 0x78, 0x6f,
	0x57, 0xea, 0x5f, 0x42, 0x53, 0x25, 0x0b, 0xbc, 0x92, 0x24, 0x05, 0x28, 0xf9, 0x26, 0x9e, 0x2c,
	0x59, 0xd0, 0x91, 0x71, 0x1f, 0xcc, 0x19, 0xa5, 0x81, 0x1a, 0x40, 0x83, 0x87, 0x32, 0xb6, 0xbf,
	0x18, 0x68, 0xe9, 0x05, 0x64, 0xc0, 0x88, 0x00, 0x4c, 0x32, 0x9f, 0xa6, 0x5a, 0x1c, 0x86, 0xb3,
	0x02, 0xb8, 0xb0, 0x9e, 0xa2, 0x19, 0xb5, 0x99, 0xb4, 0x5a, 0x95, 0xfa, 0xfa, 0xf4, 0x66, 0xc3,
	0x19, 0x74, 0xcb, 0x19, 0x5c, 0x26, 0x36, 0xc5, 0xe0, 0x6a, 0xd7, 0x91, 0x6c, 0xe6, 0x29, 0xee,
	0x48, 0x6b, 0xb4, 0x3d, 0xbd, 0x39, 0x3f, 0xcc, 0xad, 0x66, 0xc0, 0x13, 0x25, 0x0b, 0xe4, 0x61,
	0x7b, 0xeb, 0xeb, 0xa7, 0xc7, 0x95, 0xd1, 0x4e, 0x97, 0x70, 0x70, 0xca, 0x8d, 0x2e, 0x08, 0xb2,
	0xe1, 0x1c, 0xf0, 0xf0, 0xdd, 0xcf, 0x8f, 0x6b, 0x73, 0x7e, 0xc9, 0x5d, 0x7e, 0x56, 0x10, 0x06,
	0xbe, 0xcb, 0xb4, 0x4e, 0xfb, 0x83, 0x81, 0x96, 0x6f, 0x9f, 0x83, 0xe7, 0x34, 0xe3, 0xf0, 0x37,
	0x8b, 0x9f, 0x21, 0x93, 0x0d, 0xd0, 0x94, 0xd4, 0xa9, 0x9d, 0x95, 0x8b, 0xab, 0xd5, 0xda, 0xf7,
	0xab, 0xd5, 0x79, 0x2d, 0x87, 0xfb, 0xa7, 0x4e, 0x4c, 0xdd, 0x94, 0x88, 0xc8, 0xd9, 0xcf, 0x04,
	0x1e, 0xa2, 0x6c, 0x2f, 0xdd, 0xa1, 0xdb, 0x9e, 0x43, 0xb3, 0xbb, 0x9d, 0x23, 0x0c, 0xbc, 0x48,
	0x44, 0x5f, 0xd3, 0xe6, 0x2f, 0x03, 0x99, 0x1d, 0xbc, 0x77, 0xc0, 0xc3, 0x23, 0x75, 0x13, 0xac,
	0x37, 0x68, 0xf9, 0x25, 0xc9, 0xfc, 0x04, 0x3a, 0x78, 0xef, 0x36, 0x37, 0x1e, 0x0d, 0xaf, 0xee,
	0x0e, 0xe3, 0x1a, 0x6b, 0xff, 0x52, 0xaa, 0x75, 0xd8, 0x35, 0x8b, 0xf4, 0xe5, 0xc9, 0x84, 0x96,
	0xc0, 0xfe, 0xa7, 0xdb, 0xea, 0x70, 0xe9, 0x1f, 0xa3, 0xda, 0xb5, 0x9d, 0xf5, 0x8b, 0xeb, 0xa6,
	0x71, 0x79, 0xdd, 0x34, 0x7e, 0x5c, 0x37, 0x8d, 0xf7, 0xbd, 0x66, 0xed, 0xb2, 0xd7, 0xac, 0x7d,
	0xeb, 0x35, 0x6b, 0xaf, 0x17, 0x6e, 0x1e, 0x06, 0xe9, 0xac, 0x7c, 0x1c, 0xc4, 0xdb, 0x1c, 0x78,
	0x77, 0x5c, 0xdd, 0xd6, 0xad, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x30, 0x87, 0x04, 0x39,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VRFMsgServerClient is the client API for VRFMsgServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VRFMsgServerClient interface {
	HandleVRFRandomNumberRequest(ctx context.Context, in *GenerateRandomNumberRequest, opts ...grpc.CallOption) (*GenerateRandomNumberResponse, error)
	DVSResponsHandler(ctx context.Context, in *GenerateRandomNumberRequest, opts ...grpc.CallOption) (*DVSResultResponse, error)
}

type vRFMsgServerClient struct {
	cc grpc1.ClientConn
}

func NewVRFMsgServerClient(cc grpc1.ClientConn) VRFMsgServerClient {
	return &vRFMsgServerClient{cc}
}

func (c *vRFMsgServerClient) HandleVRFRandomNumberRequest(ctx context.Context, in *GenerateRandomNumberRequest, opts ...grpc.CallOption) (*GenerateRandomNumberResponse, error) {
	out := new(GenerateRandomNumberResponse)
	err := c.cc.Invoke(ctx, "/intellix.vrf.VRFMsgServer/HandleVRFRandomNumberRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vRFMsgServerClient) DVSResponsHandler(ctx context.Context, in *GenerateRandomNumberRequest, opts ...grpc.CallOption) (*DVSResultResponse, error) {
	out := new(DVSResultResponse)
	err := c.cc.Invoke(ctx, "/intellix.vrf.VRFMsgServer/DVSResponsHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VRFMsgServerServer is the server API for VRFMsgServer service.
type VRFMsgServerServer interface {
	HandleVRFRandomNumberRequest(context.Context, *GenerateRandomNumberRequest) (*GenerateRandomNumberResponse, error)
	DVSResponsHandler(context.Context, *GenerateRandomNumberRequest) (*DVSResultResponse, error)
}

// UnimplementedVRFMsgServerServer can be embedded to have forward compatible implementations.
type UnimplementedVRFMsgServerServer struct {
}

func (*UnimplementedVRFMsgServerServer) HandleVRFRandomNumberRequest(ctx context.Context, req *GenerateRandomNumberRequest) (*GenerateRandomNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleVRFRandomNumberRequest not implemented")
}
func (*UnimplementedVRFMsgServerServer) DVSResponsHandler(ctx context.Context, req *GenerateRandomNumberRequest) (*DVSResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DVSResponsHandler not implemented")
}

func RegisterVRFMsgServerServer(s grpc1.Server, srv VRFMsgServerServer) {
	s.RegisterService(&_VRFMsgServer_serviceDesc, srv)
}

func _VRFMsgServer_HandleVRFRandomNumberRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRandomNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VRFMsgServerServer).HandleVRFRandomNumberRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intellix.vrf.VRFMsgServer/HandleVRFRandomNumberRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VRFMsgServerServer).HandleVRFRandomNumberRequest(ctx, req.(*GenerateRandomNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VRFMsgServer_DVSResponsHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRandomNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VRFMsgServerServer).DVSResponsHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intellix.vrf.VRFMsgServer/DVSResponsHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VRFMsgServerServer).DVSResponsHandler(ctx, req.(*GenerateRandomNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var VRFMsgServer_serviceDesc = _VRFMsgServer_serviceDesc
var _VRFMsgServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intellix.vrf.VRFMsgServer",
	HandlerType: (*VRFMsgServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleVRFRandomNumberRequest",
			Handler:    _VRFMsgServer_HandleVRFRandomNumberRequest_Handler,
		},
		{
			MethodName: "DVSResponsHandler",
			Handler:    _VRFMsgServer_DVSResponsHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intellix/vrf/msg_server.proto",
}

func (m *TaskMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GroupThresholdPercentage != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.GroupThresholdPercentage))
		i--
		dAtA[i] = 0x28
	}
	if len(m.GroupNumbers) > 0 {
		i -= len(m.GroupNumbers)
		copy(dAtA[i:], m.GroupNumbers)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.GroupNumbers)))
		i--
		dAtA[i] = 0x22
	}
	if m.ChainId != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x18
	}
	if m.Height != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.TaskIndex != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VRFData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VRFData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VRFData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VrfProof) > 0 {
		i -= len(m.VrfProof)
		copy(dAtA[i:], m.VrfProof)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.VrfProof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VrfValue) > 0 {
		i -= len(m.VrfValue)
		copy(dAtA[i:], m.VrfValue)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.VrfValue)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateRandomNumberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateRandomNumberRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateRandomNumberRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VrfData) > 0 {
		for iNdEx := len(m.VrfData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VrfData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgServer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TaskMetadata != nil {
		{
			size, err := m.TaskMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgServer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateRandomNumberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateRandomNumberResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateRandomNumberResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RandomNumber) > 0 {
		for iNdEx := len(m.RandomNumber) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.RandomNumber[iNdEx].Size()
				i -= size
				if _, err := m.RandomNumber[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintMsgServer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TaskIndex != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DVSResultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DVSResultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DVSResultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsgServer(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgServer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TaskMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovMsgServer(uint64(m.TaskIndex))
	}
	if m.Height != 0 {
		n += 1 + sovMsgServer(uint64(m.Height))
	}
	if m.ChainId != 0 {
		n += 1 + sovMsgServer(uint64(m.ChainId))
	}
	l = len(m.GroupNumbers)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	if m.GroupThresholdPercentage != 0 {
		n += 1 + sovMsgServer(uint64(m.GroupThresholdPercentage))
	}
	return n
}

func (m *VRFData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VrfValue)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = len(m.VrfProof)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	return n
}

func (m *GenerateRandomNumberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskMetadata != nil {
		l = m.TaskMetadata.Size()
		n += 1 + l + sovMsgServer(uint64(l))
	}
	if len(m.VrfData) > 0 {
		for _, e := range m.VrfData {
			l = e.Size()
			n += 1 + l + sovMsgServer(uint64(l))
		}
	}
	return n
}

func (m *GenerateRandomNumberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovMsgServer(uint64(m.TaskIndex))
	}
	if len(m.RandomNumber) > 0 {
		for _, e := range m.RandomNumber {
			l = e.Size()
			n += 1 + l + sovMsgServer(uint64(l))
		}
	}
	return n
}

func (m *DVSResultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsgServer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgServer(x uint64) (n int) {
	return sovMsgServer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TaskMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNumbers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupNumbers = append(m.GroupNumbers[:0], dAtA[iNdEx:postIndex]...)
			if m.GroupNumbers == nil {
				m.GroupNumbers = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupThresholdPercentage", wireType)
			}
			m.GroupThresholdPercentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupThresholdPercentage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VRFData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VRFData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VRFData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfValue = append(m.VrfValue[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfValue == nil {
				m.VrfValue = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfProof = append(m.VrfProof[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfProof == nil {
				m.VrfProof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateRandomNumberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateRandomNumberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateRandomNumberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskMetadata == nil {
				m.TaskMetadata = &TaskMetadata{}
			}
			if err := m.TaskMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfData = append(m.VrfData, &VRFData{})
			if err := m.VrfData[len(m.VrfData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateRandomNumberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateRandomNumberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateRandomNumberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.RandomNumber = append(m.RandomNumber, v)
			if err := m.RandomNumber[len(m.RandomNumber)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DVSResultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DVSResultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DVSResultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgServer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgServer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgServer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgServer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgServer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgServer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgServer = fmt.Errorf("proto: unexpected end of group")
)
