syntax = "proto3";
package intellix.vrf;

import "gogoproto/gogo.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "intellix/dvs/vrf/types";

service VRFMsgRequest {
  rpc HandleVRFRandomNumberRequest(VRFTaskRequest) returns (VRFTaskResponse) {}
}

service VRFMsgResponse {
  rpc DVSResponsHandler(VRFTaskRequest) returns (DVSResultResponse) {}
}

message TaskMetadata {
  uint32 task_index = 1;
  bytes request_id = 2;
  string fee_token = 3;
  string payment = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];
  bytes request_data = 5;
  string callback_address = 6;
  bytes callback_function_id = 7;
  uint32 task_created_block = 8;
  bytes group_numbers = 9;
  uint32 group_threshold_percentage = 10;
  bool advance_decode = 11;
}

message VRFData {
  bytes vrf_value = 1;
  bytes vrf_proof = 2;
}

message VRFTaskRequest {
  option (cosmos_proto.implements_interface) = "cosmos.base.v1beta1.Msg";
  option (amino.name) = "dvs/squared/request";
  TaskMetadata task_metadata = 1;
  repeated VRFData vrf_data = 2;
}

message VRFTaskResponse {
  option (cosmos_proto.implements_interface) = "cosmos.base.v1beta1.Msg";
  uint32 task_index = 1;
  repeated string randomNumber = 2 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];
}

message DVSResultResponse {}
