name: cd-testnet-operator
# Runs the CI end-to-end test network on all pushes to v0.38.x
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch: # allow running workflow manually
  pull_request:
    branches:
      - feat/devnet
    paths:
      - '.github/workflows/cd-testnet-operator.yml'
      - 'docker/devnet/operator/*.sh'
      - 'docker/devnet/docker-compose.yml'
  push:
    branches:
      - feat/devnet
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/cd-testnet-operator.yml'
      - 'docker/devnet/operator/*.sh'
      - 'docker/devnet/docker-compose.yml'
jobs:
  deploy-staging:
    runs-on: [ "self-hosted", "Linux", "X64", "devnet" ]
    timeout-minutes: 30
    env:
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
      COMPOSE_PROJECT: intellix-testnet
      GITHUB_TOKEN: ${{ secrets.TESTNET_GH_TOKEN }}
      REGISTRY_ROUTER_ADDRESS: ${{ vars.TESTNET_REGISTRY_ROUTER_ADDRESS }}
      SERVICE_CHAIN_RPC_URL: ${{ secrets.TESTNET_SERVICE_CHAIN_RPC_URL }}
      SERVICE_CHAIN_WS_URL: ${{ secrets.TESTNET_SERVICE_CHAIN_WS_URL }}
      CHAIN_ID: ${{ vars.TESTNET_SERVICE_CHAIN_ID }}
      NETWORK: ${{ vars.TESTNET_NETWORK }}
      DISPATCHER_HOST_DEBUG_PORT: 23346
      DISPATCHER_HOST_SERVER_PORT: 23389
      DISPATCHER_HOST_PELLDVS_HOME: /home/ubuntu/.intellix-homes/intellix-testnet/dispatcher
      OPERATOR_HOST_SERVER_PORT: 37757
      OPERATOR_HOST_DEBUG_PORT: 33347
      OPERATOR_KEY: ${{ secrets.TESTNET_OPERATOR_KEY }}
      OPERATOR_KEY_MNEMONIC: ${{ secrets.TESTNET_OPERATOR_KEY_MNEMONIC }}
      OPERATOR_HOST_PELLDVS_HOME: /home/ubuntu/.intellix-homes/intellix-testnet/operator
      ETH_RPC_URL: https://pevm.pell.dev
      GATEWAY_ADDR: gateway:8949
    steps:
      - name: trigger deploy
        run: |
          echo "trigger deploy by update this file"

      - name: Setup new work dir
        id: setup_new_work_dir
        run: |
          CLEAN_WORKFLOW_NAME=$(echo "${{ github.workflow }}" | tr -cs '[:alnum:]' '_')
          CLEAN_JOB_NAME=$(echo "${{ github.job }}" | tr -cs '[:alnum:]' '_')
          echo "NEW_WORK_DIR=./deploys/${CLEAN_WORKFLOW_NAME}/${CLEAN_JOB_NAME}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          path: ${{ env.NEW_WORK_DIR }}

      - name: ensure home dir
        run: |
          mkdir -p ${DISPATCHER_HOST_PELLDVS_HOME}
          mkdir -p ${OPERATOR_HOST_PELLDVS_HOME}

      - name: setup github private repo access
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"

      - name: Build docker images
        run: |
          docker compose -p ${{ env.COMPOSE_PROJECT }} -f docker-compose.build.yml build operator
        working-directory: ${{ env.NEW_WORK_DIR }}/docker

      - name: Shutdown services
        run: |
          docker compose -p ${COMPOSE_PROJECT} -f docker-compose.yml down
        working-directory: ${{ env.NEW_WORK_DIR }}/docker/devnet

      - name: Start services - operator - dispatcher
        run: |
          ENV_FILE=./.env-operator-dispatcher
          rm -rf ${ENV_FILE}
          
          echo "# env - ${ENV_FILE} " >> ${ENV_FILE}
          echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> ${ENV_FILE}
          echo "SERVICE_CHAIN_RPC_URL=${SERVICE_CHAIN_RPC_URL}" >> ${ENV_FILE}
          echo "SERVICE_CHAIN_WS_URL=${SERVICE_CHAIN_WS_URL}" >> ${ENV_FILE}
          echo "REGISTRY_ROUTER_ADDRESS=${REGISTRY_ROUTER_ADDRESS}" >> ${ENV_FILE}
          echo "ETH_RPC_URL=${ETH_RPC_URL}" >> ${ENV_FILE}
          echo "NETWORK=${NETWORK}" >> ${ENV_FILE}
          echo "CHAIN_ID=${CHAIN_ID}" >> ${ENV_FILE}
          echo "HOST_PELLDVS_HOME=${DISPATCHER_HOST_PELLDVS_HOME}" >> ${ENV_FILE}
          echo "" >> ${ENV_FILE}
          
          docker compose -p ${COMPOSE_PROJECT} -f docker-compose.yml --env-file ${ENV_FILE} up -d dispatcher
        working-directory: ${{ env.NEW_WORK_DIR }}/docker/devnet
        env:
          HOST_DEBUG_PORT: 33346
          OPERATOR_HOST_PORT: 36657
          ETH_RPC_URL: https://pevm.pell.dev

      - name: Start services - operator - operator
        run: |
          ENV_FILE=./.env-operator-operator
          rm -rf ${ENV_FILE}
          
          echo "# env - ${ENV_FILE} " >> ${ENV_FILE}
          
          echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> ${ENV_FILE}
          echo "REGISTRY_ROUTER_ADDRESS=${REGISTRY_ROUTER_ADDRESS}" >> ${ENV_FILE}
          echo "ETH_RPC_URL=${ETH_RPC_URL}" >> ${ENV_FILE}
          echo "NETWORK=${NETWORK}" >> ${ENV_FILE}
          echo "CHAIN_ID=${CHAIN_ID}" >> ${ENV_FILE}
          
          echo "HOST_PELLDVS_HOME=${OPERATOR_HOST_PELLDVS_HOME}" >> ${ENV_FILE}
          
          echo "GATEWAY_ADDR=${GATEWAY_ADDR}" >> ${ENV_FILE}
          
          echo "OPERATOR_KEY=${{ secrets.TESTNET_OPERATOR_KEY }}" >> ${ENV_FILE}
          echo "OPERATOR_KEY_MNEMONIC=${OPERATOR_KEY_MNEMONIC}" >> ${ENV_FILE}
          echo "HOST_SERVER_PORT=${OPERATOR_HOST_SERVER_PORT}" >> ${ENV_FILE}
          echo "" >> ${ENV_FILE}
          
          docker compose -p ${COMPOSE_PROJECT} -f docker-compose.yml --env-file ${ENV_FILE} up -d operator
        working-directory: ${{ env.NEW_WORK_DIR }}/docker/devnet
        env:
          HOST_DEBUG_PORT: 33347
          ETH_RPC_URL: https://pevm.pell.dev
          GATEWAY_ADDR: gateway:8949
