name: e2e
# Runs the CI end-to-end test network on all pushes to v0.38.x
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch: # allow running workflow manually
  pull_request:
  push:
    branches:
      - master
concurrency: 
  group: e2e-test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          ref: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: setup go private modules
        env:
          PELL_GH_TOKEN: ${{ secrets.PELL_GH_TOKEN }}
          INTELLIX_GH_TOKEN: ${{ secrets.INTELLIX_GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          go env -w GOPRIVATE=github.com/0xPellNetwork,github.com/IntelliXLabs
          go env -w GONOSUMDB=github.com/0xPellNetwork,github.com/IntelliXLabs
          git config --global url."https://${PELL_GH_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
          git config --global url."https://${INTELLIX_GH_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"
      - name: Build docker images
        run: make docker-build-all
      - name: Stop services
        run: make docker-all-down
      - name: Start services
        run: make docker-operator-up
      - name: sleep 60 seconds
        run: sleep 60
      - name: Test services
        run: cd docker && docker compose run --rm test /root/scripts/test.sh
      - name: Print logs
        run: make docker-all-logs-in-ci
        if: always()
      - name: Stop services
        run: make docker-all-down
        if: always()
