name: Test
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
  push:
    branches:
      - master
    paths:
      - "**.go"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup new work dir
        id: setup_new_work_dir
        run: |
          CLEAN_WORKFLOW_NAME=$(echo "${{ github.workflow }}" | tr -cs '[:alnum:]' '_')
          CLEAN_JOB_NAME=$(echo "${{ github.job }}" | tr -cs '[:alnum:]' '_')
          echo "NEW_WORK_DIR=./codes/${CLEAN_WORKFLOW_NAME}/${CLEAN_JOB_NAME}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - uses: actions/checkout@v4
        with:
          path: ${{ env.NEW_WORK_DIR }}
#      - uses: technote-space/get-diff-action@v6
#        with:
#          RELATIVE: ${{ env.NEW_WORK_DIR }}
#          PATTERNS: |
#            **/**.go
#            "!test/"
#            go.mod
#            go.sum
#            Makefile
      - name: setup go private modules
        env:
          PELL_GH_TOKEN: ${{ secrets.PELL_GH_TOKEN }}
          INTELLIX_GH_TOKEN: ${{ secrets.INTELLIX_GH_TOKEN }}
        run: |
          go env -w GOPRIVATE=github.com/0xPellNetwork,github.com/IntelliXLabs
          go env -w GONOSUMDB=github.com/0xPellNetwork,github.com/IntelliXLabs
          git config --global url."https://${PELL_GH_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
          git config --global url."https://${INTELLIX_GH_TOKEN}:x-oauth-basic@github.com/IntelliXLabs".insteadOf "https://github.com/IntelliXLabs"
      - name: download go modules
        run: go mod download
        working-directory: ${{ env.NEW_WORK_DIR }}
      - name: Run Go Tests
        working-directory: ${{ env.NEW_WORK_DIR }}
        run: |
          make test-in-ci
