// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intellix/processor/dvs/msg_server.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DVSResponsHandlerResponse represents an empty response message for script
// execution. Currently empty as no specific response data is needed.
type DVSResponsHandlerResponse struct {
}

func (m *DVSResponsHandlerResponse) Reset()         { *m = DVSResponsHandlerResponse{} }
func (m *DVSResponsHandlerResponse) String() string { return proto.CompactTextString(m) }
func (*DVSResponsHandlerResponse) ProtoMessage()    {}
func (*DVSResponsHandlerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d4389d7e39fc053, []int{0}
}
func (m *DVSResponsHandlerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DVSResponsHandlerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DVSResponsHandlerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DVSResponsHandlerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DVSResponsHandlerResponse.Merge(m, src)
}
func (m *DVSResponsHandlerResponse) XXX_Size() int {
	return m.Size()
}
func (m *DVSResponsHandlerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DVSResponsHandlerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DVSResponsHandlerResponse proto.InternalMessageInfo

// RequestScriptIn represents a request for script execution in the DVS system.
// Contains all necessary parameters for processing a script request including
// task information, payment details, and execution parameters.
type RequestScriptIn struct {
	TaskIndex                 uint32                `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	RequestId                 []byte                `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FeeToken                  string                `protobuf:"bytes,3,opt,name=fee_token,json=feeToken,proto3" json:"fee_token,omitempty"`
	Payment                   cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=payment,proto3,customtype=cosmossdk.io/math.Int" json:"payment"`
	RequestData               []byte                `protobuf:"bytes,5,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
	CallbackAddress           string                `protobuf:"bytes,6,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"`
	CallbackFunctionId        []byte                `protobuf:"bytes,7,opt,name=callback_function_id,json=callbackFunctionId,proto3" json:"callback_function_id,omitempty"`
	TaskCreatedBlock          uint32                `protobuf:"varint,8,opt,name=task_created_block,json=taskCreatedBlock,proto3" json:"task_created_block,omitempty"`
	QuorumNumbers             []byte                `protobuf:"bytes,9,opt,name=quorum_numbers,json=quorumNumbers,proto3" json:"quorum_numbers,omitempty"`
	QuorumThresholdPercentage uint32                `protobuf:"varint,10,opt,name=quorum_threshold_percentage,json=quorumThresholdPercentage,proto3" json:"quorum_threshold_percentage,omitempty"`
	ScriptId                  uint64                `protobuf:"varint,11,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	ScriptParam               []byte                `protobuf:"bytes,12,opt,name=script_param,json=scriptParam,proto3" json:"script_param,omitempty"`
	AdvanceDecode             bool                  `protobuf:"varint,13,opt,name=advance_decode,json=advanceDecode,proto3" json:"advance_decode,omitempty"`
}

func (m *RequestScriptIn) Reset()         { *m = RequestScriptIn{} }
func (m *RequestScriptIn) String() string { return proto.CompactTextString(m) }
func (*RequestScriptIn) ProtoMessage()    {}
func (*RequestScriptIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d4389d7e39fc053, []int{1}
}
func (m *RequestScriptIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestScriptIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestScriptIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestScriptIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestScriptIn.Merge(m, src)
}
func (m *RequestScriptIn) XXX_Size() int {
	return m.Size()
}
func (m *RequestScriptIn) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestScriptIn.DiscardUnknown(m)
}

var xxx_messageInfo_RequestScriptIn proto.InternalMessageInfo

func (m *RequestScriptIn) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *RequestScriptIn) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *RequestScriptIn) GetFeeToken() string {
	if m != nil {
		return m.FeeToken
	}
	return ""
}

func (m *RequestScriptIn) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *RequestScriptIn) GetCallbackAddress() string {
	if m != nil {
		return m.CallbackAddress
	}
	return ""
}

func (m *RequestScriptIn) GetCallbackFunctionId() []byte {
	if m != nil {
		return m.CallbackFunctionId
	}
	return nil
}

func (m *RequestScriptIn) GetTaskCreatedBlock() uint32 {
	if m != nil {
		return m.TaskCreatedBlock
	}
	return 0
}

func (m *RequestScriptIn) GetQuorumNumbers() []byte {
	if m != nil {
		return m.QuorumNumbers
	}
	return nil
}

func (m *RequestScriptIn) GetQuorumThresholdPercentage() uint32 {
	if m != nil {
		return m.QuorumThresholdPercentage
	}
	return 0
}

func (m *RequestScriptIn) GetScriptId() uint64 {
	if m != nil {
		return m.ScriptId
	}
	return 0
}

func (m *RequestScriptIn) GetScriptParam() []byte {
	if m != nil {
		return m.ScriptParam
	}
	return nil
}

func (m *RequestScriptIn) GetAdvanceDecode() bool {
	if m != nil {
		return m.AdvanceDecode
	}
	return false
}

// RequestScriptResponse represents the output of a script execution request.
// Contains the execution results and verification data.
type RequestScriptResponse struct {
	TaskIndex     uint32 `protobuf:"varint,1,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	ScriptOutData []byte `protobuf:"bytes,2,opt,name=script_out_data,json=scriptOutData,proto3" json:"script_out_data,omitempty"`
	DataDigest    []byte `protobuf:"bytes,3,opt,name=data_digest,json=dataDigest,proto3" json:"data_digest,omitempty"`
}

func (m *RequestScriptResponse) Reset()         { *m = RequestScriptResponse{} }
func (m *RequestScriptResponse) String() string { return proto.CompactTextString(m) }
func (*RequestScriptResponse) ProtoMessage()    {}
func (*RequestScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d4389d7e39fc053, []int{2}
}
func (m *RequestScriptResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestScriptResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestScriptResponse.Merge(m, src)
}
func (m *RequestScriptResponse) XXX_Size() int {
	return m.Size()
}
func (m *RequestScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestScriptResponse proto.InternalMessageInfo

func (m *RequestScriptResponse) GetTaskIndex() uint32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *RequestScriptResponse) GetScriptOutData() []byte {
	if m != nil {
		return m.ScriptOutData
	}
	return nil
}

func (m *RequestScriptResponse) GetDataDigest() []byte {
	if m != nil {
		return m.DataDigest
	}
	return nil
}

func init() {
	proto.RegisterType((*DVSResponsHandlerResponse)(nil), "intellix.processor.dvs.DVSResponsHandlerResponse")
	proto.RegisterType((*RequestScriptIn)(nil), "intellix.processor.dvs.RequestScriptIn")
	proto.RegisterType((*RequestScriptResponse)(nil), "intellix.processor.dvs.RequestScriptResponse")
}

func init() {
	proto.RegisterFile("intellix/processor/dvs/msg_server.proto", fileDescriptor_3d4389d7e39fc053)
}

var fileDescriptor_3d4389d7e39fc053 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x1b, 0x18, 0x5b, 0xeb, 0xb5, 0x6c, 0x58, 0x1b, 0x64, 0x2b, 0xeb, 0xca, 0x24, 0x58,
	0x91, 0x58, 0xca, 0x40, 0x02, 0x89, 0x03, 0x12, 0xa3, 0x42, 0xf4, 0x00, 0x4c, 0xd9, 0xc4, 0x81,
	0x4b, 0xe4, 0xc6, 0xdf, 0xb2, 0xa8, 0x89, 0x9d, 0xd9, 0x4e, 0xb5, 0x9d, 0xf8, 0x0b, 0xfc, 0x18,
	0xce, 0x9c, 0x27, 0x4e, 0x3b, 0x22, 0x0e, 0x13, 0x5a, 0x6f, 0xfc, 0x0a, 0x64, 0x3b, 0x29, 0x1a,
	0x30, 0xb1, 0x5b, 0xfc, 0xbc, 0x6f, 0xec, 0xcf, 0x9f, 0x5f, 0x1b, 0xad, 0xc7, 0x4c, 0x41, 0x92,
	0xc4, 0x87, 0xdd, 0x4c, 0xf0, 0x10, 0xa4, 0xe4, 0xa2, 0x4b, 0x47, 0xb2, 0x9b, 0xca, 0x28, 0x90,
	0x20, 0x46, 0x20, 0xbc, 0x4c, 0x70, 0xc5, 0xf1, 0xcd, 0xd2, 0xe8, 0x4d, 0x8c, 0x1e, 0x1d, 0xc9,
	0xe5, 0xa5, 0x90, 0xcb, 0x94, 0xcb, 0xc0, 0xb8, 0xba, 0x76, 0x60, 0x7f, 0x59, 0x5e, 0x88, 0x78,
	0xc4, 0x2d, 0xd7, 0x5f, 0x96, 0xae, 0x35, 0xd1, 0x52, 0xef, 0xfd, 0x8e, 0x0f, 0x32, 0xe3, 0x4c,
	0xbe, 0x26, 0x8c, 0x26, 0x20, 0x8a, 0x11, 0xac, 0x7d, 0x99, 0x42, 0x73, 0x3e, 0x1c, 0xe4, 0x20,
	0xd5, 0x4e, 0x28, 0xe2, 0x4c, 0xf5, 0x19, 0x5e, 0x41, 0x48, 0x11, 0x39, 0x0c, 0x62, 0x46, 0xe1,
	0xd0, 0x75, 0xda, 0x4e, 0xa7, 0xe1, 0xd7, 0x34, 0xe9, 0x6b, 0xa0, 0x65, 0x61, 0xff, 0x08, 0x62,
	0xea, 0x5e, 0x69, 0x3b, 0x9d, 0xba, 0x5f, 0x2b, 0x48, 0x9f, 0xe2, 0x26, 0xaa, 0xed, 0x01, 0x04,
	0x8a, 0x0f, 0x81, 0xb9, 0x57, 0xdb, 0x4e, 0xa7, 0xe6, 0x57, 0xf7, 0x00, 0x76, 0xf5, 0x18, 0x3f,
	0x45, 0x33, 0x19, 0x39, 0x4a, 0x81, 0x29, 0x77, 0x4a, 0x4b, 0x5b, 0x2b, 0xc7, 0xa7, 0xab, 0x95,
	0xef, 0xa7, 0xab, 0x8b, 0x76, 0x23, 0x92, 0x0e, 0xbd, 0x98, 0x77, 0x53, 0xa2, 0xf6, 0xbd, 0x3e,
	0x53, 0x7e, 0xe9, 0xc6, 0x77, 0x50, 0xbd, 0x5c, 0x94, 0x12, 0x45, 0xdc, 0x6b, 0x66, 0xd9, 0xd9,
	0x82, 0xf5, 0x88, 0x22, 0xf8, 0x3e, 0x9a, 0x0f, 0x49, 0x92, 0x0c, 0x48, 0x38, 0x0c, 0x08, 0xa5,
	0x02, 0xa4, 0x74, 0xa7, 0xcd, 0xfa, 0x73, 0x25, 0x7f, 0x61, 0x31, 0x7e, 0x88, 0x16, 0x26, 0xd6,
	0xbd, 0x9c, 0x85, 0x2a, 0xe6, 0x4c, 0x6f, 0x66, 0xc6, 0xcc, 0x8a, 0x4b, 0xed, 0x55, 0x21, 0xf5,
	0x29, 0x7e, 0x80, 0xb0, 0xe9, 0x49, 0x28, 0x80, 0x28, 0xa0, 0xc1, 0x20, 0xe1, 0xe1, 0xd0, 0xad,
	0x9a, 0xde, 0xcc, 0x6b, 0xe5, 0xa5, 0x15, 0xb6, 0x34, 0xc7, 0x77, 0xd1, 0xf5, 0x83, 0x9c, 0x8b,
	0x3c, 0x0d, 0x58, 0x9e, 0x0e, 0x40, 0x48, 0xb7, 0x66, 0x66, 0x6e, 0x58, 0xfa, 0xd6, 0x42, 0xfc,
	0x1c, 0x35, 0x0b, 0x9b, 0xda, 0x17, 0x20, 0xf7, 0x79, 0x42, 0x83, 0x0c, 0x44, 0x08, 0x4c, 0x91,
	0x08, 0x5c, 0x64, 0x66, 0x5f, 0xb2, 0x96, 0xdd, 0xd2, 0xb1, 0x3d, 0x31, 0xe8, 0x56, 0x4b, 0x73,
	0x68, 0xba, 0xf6, 0xd9, 0xb6, 0xd3, 0x99, 0xf2, 0xab, 0x16, 0xf4, 0xa9, 0xee, 0x58, 0x21, 0x66,
	0x44, 0x90, 0xd4, 0xad, 0xdb, 0x8e, 0x59, 0xb6, 0xad, 0x91, 0x2e, 0x93, 0xd0, 0x11, 0x61, 0x21,
	0x04, 0x14, 0x42, 0x4e, 0xc1, 0x6d, 0xb4, 0x9d, 0x4e, 0xd5, 0x6f, 0x14, 0xb4, 0x67, 0xe0, 0xb3,
	0xe6, 0xd7, 0xcf, 0x1b, 0xb7, 0x8a, 0xa0, 0x0d, 0x88, 0x04, 0x6f, 0xb4, 0x39, 0x00, 0x45, 0x36,
	0xbd, 0x37, 0x32, 0x5a, 0xfb, 0x88, 0x16, 0xcf, 0xe5, 0xa7, 0x4c, 0xd6, 0xff, 0x52, 0x74, 0x0f,
	0xcd, 0x15, 0xe5, 0xf1, 0xbc, 0x38, 0x53, 0x1b, 0xa5, 0x86, 0xc5, 0xef, 0x72, 0x7b, 0xaa, 0xab,
	0x68, 0x56, 0x8b, 0x01, 0x8d, 0x23, 0x90, 0xca, 0x04, 0xaa, 0xee, 0x23, 0x8d, 0x7a, 0x86, 0x3c,
	0xfa, 0xe9, 0x20, 0x64, 0xf2, 0x6d, 0x8a, 0xc0, 0x31, 0x6a, 0x9c, 0xab, 0x07, 0xaf, 0x7b, 0xff,
	0xbe, 0x48, 0xde, 0x1f, 0xb1, 0x5f, 0xde, 0xb8, 0x94, 0x71, 0x72, 0x73, 0x2a, 0xf8, 0x00, 0xdd,
	0xf8, 0xeb, 0x62, 0x5d, 0x7e, 0xb9, 0xcd, 0x8b, 0x8c, 0x17, 0x5f, 0xd6, 0xca, 0xd6, 0x93, 0xe3,
	0xb3, 0x96, 0x73, 0x72, 0xd6, 0x72, 0x7e, 0x9c, 0xb5, 0x9c, 0x4f, 0xe3, 0x56, 0xe5, 0x64, 0xdc,
	0xaa, 0x7c, 0x1b, 0xb7, 0x2a, 0x1f, 0x6e, 0x4f, 0xde, 0x15, 0xfd, 0x9a, 0xfc, 0x7e, 0x5b, 0xd4,
	0x51, 0x06, 0x72, 0x30, 0x6d, 0x9e, 0x82, 0xc7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x6e,
	0x9a, 0xff, 0x7e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DVSRequestClient is the client API for DVSRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DVSRequestClient interface {
	// RequestScript processes a script execution request
	RequestScript(ctx context.Context, in *RequestScriptIn, opts ...grpc.CallOption) (*RequestScriptResponse, error)
	// DVSResponsHandler handles the response processing for DVS requests
	DVSResponsHandler(ctx context.Context, in *RequestScriptIn, opts ...grpc.CallOption) (*DVSResponsHandlerResponse, error)
}

type dVSRequestClient struct {
	cc grpc1.ClientConn
}

func NewDVSRequestClient(cc grpc1.ClientConn) DVSRequestClient {
	return &dVSRequestClient{cc}
}

func (c *dVSRequestClient) RequestScript(ctx context.Context, in *RequestScriptIn, opts ...grpc.CallOption) (*RequestScriptResponse, error) {
	out := new(RequestScriptResponse)
	err := c.cc.Invoke(ctx, "/intellix.processor.dvs.DVSRequest/RequestScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dVSRequestClient) DVSResponsHandler(ctx context.Context, in *RequestScriptIn, opts ...grpc.CallOption) (*DVSResponsHandlerResponse, error) {
	out := new(DVSResponsHandlerResponse)
	err := c.cc.Invoke(ctx, "/intellix.processor.dvs.DVSRequest/DVSResponsHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DVSRequestServer is the server API for DVSRequest service.
type DVSRequestServer interface {
	// RequestScript processes a script execution request
	RequestScript(context.Context, *RequestScriptIn) (*RequestScriptResponse, error)
	// DVSResponsHandler handles the response processing for DVS requests
	DVSResponsHandler(context.Context, *RequestScriptIn) (*DVSResponsHandlerResponse, error)
}

// UnimplementedDVSRequestServer can be embedded to have forward compatible implementations.
type UnimplementedDVSRequestServer struct {
}

func (*UnimplementedDVSRequestServer) RequestScript(ctx context.Context, req *RequestScriptIn) (*RequestScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestScript not implemented")
}
func (*UnimplementedDVSRequestServer) DVSResponsHandler(ctx context.Context, req *RequestScriptIn) (*DVSResponsHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DVSResponsHandler not implemented")
}

func RegisterDVSRequestServer(s grpc1.Server, srv DVSRequestServer) {
	s.RegisterService(&_DVSRequest_serviceDesc, srv)
}

func _DVSRequest_RequestScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestScriptIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DVSRequestServer).RequestScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intellix.processor.dvs.DVSRequest/RequestScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DVSRequestServer).RequestScript(ctx, req.(*RequestScriptIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _DVSRequest_DVSResponsHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestScriptIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DVSRequestServer).DVSResponsHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intellix.processor.dvs.DVSRequest/DVSResponsHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DVSRequestServer).DVSResponsHandler(ctx, req.(*RequestScriptIn))
	}
	return interceptor(ctx, in, info, handler)
}

var DVSRequest_serviceDesc = _DVSRequest_serviceDesc
var _DVSRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intellix.processor.dvs.DVSRequest",
	HandlerType: (*DVSRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestScript",
			Handler:    _DVSRequest_RequestScript_Handler,
		},
		{
			MethodName: "DVSResponsHandler",
			Handler:    _DVSRequest_DVSResponsHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intellix/processor/dvs/msg_server.proto",
}

func (m *DVSResponsHandlerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DVSResponsHandlerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DVSResponsHandlerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *RequestScriptIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestScriptIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestScriptIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AdvanceDecode {
		i--
		if m.AdvanceDecode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if len(m.ScriptParam) > 0 {
		i -= len(m.ScriptParam)
		copy(dAtA[i:], m.ScriptParam)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.ScriptParam)))
		i--
		dAtA[i] = 0x62
	}
	if m.ScriptId != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.ScriptId))
		i--
		dAtA[i] = 0x58
	}
	if m.QuorumThresholdPercentage != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.QuorumThresholdPercentage))
		i--
		dAtA[i] = 0x50
	}
	if len(m.QuorumNumbers) > 0 {
		i -= len(m.QuorumNumbers)
		copy(dAtA[i:], m.QuorumNumbers)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.QuorumNumbers)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TaskCreatedBlock != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.TaskCreatedBlock))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CallbackFunctionId) > 0 {
		i -= len(m.CallbackFunctionId)
		copy(dAtA[i:], m.CallbackFunctionId)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.CallbackFunctionId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CallbackAddress) > 0 {
		i -= len(m.CallbackAddress)
		copy(dAtA[i:], m.CallbackAddress)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.CallbackAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequestData) > 0 {
		i -= len(m.RequestData)
		copy(dAtA[i:], m.RequestData)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.RequestData)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.Payment.Size()
		i -= size
		if _, err := m.Payment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgServer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.FeeToken) > 0 {
		i -= len(m.FeeToken)
		copy(dAtA[i:], m.FeeToken)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.FeeToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskIndex != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestScriptResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestScriptResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestScriptResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataDigest) > 0 {
		i -= len(m.DataDigest)
		copy(dAtA[i:], m.DataDigest)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.DataDigest)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ScriptOutData) > 0 {
		i -= len(m.ScriptOutData)
		copy(dAtA[i:], m.ScriptOutData)
		i = encodeVarintMsgServer(dAtA, i, uint64(len(m.ScriptOutData)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskIndex != 0 {
		i = encodeVarintMsgServer(dAtA, i, uint64(m.TaskIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgServer(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgServer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DVSResponsHandlerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *RequestScriptIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovMsgServer(uint64(m.TaskIndex))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = len(m.FeeToken)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = m.Payment.Size()
	n += 1 + l + sovMsgServer(uint64(l))
	l = len(m.RequestData)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = len(m.CallbackAddress)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = len(m.CallbackFunctionId)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	if m.TaskCreatedBlock != 0 {
		n += 1 + sovMsgServer(uint64(m.TaskCreatedBlock))
	}
	l = len(m.QuorumNumbers)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	if m.QuorumThresholdPercentage != 0 {
		n += 1 + sovMsgServer(uint64(m.QuorumThresholdPercentage))
	}
	if m.ScriptId != 0 {
		n += 1 + sovMsgServer(uint64(m.ScriptId))
	}
	l = len(m.ScriptParam)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	if m.AdvanceDecode {
		n += 2
	}
	return n
}

func (m *RequestScriptResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskIndex != 0 {
		n += 1 + sovMsgServer(uint64(m.TaskIndex))
	}
	l = len(m.ScriptOutData)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	l = len(m.DataDigest)
	if l > 0 {
		n += 1 + l + sovMsgServer(uint64(l))
	}
	return n
}

func sovMsgServer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgServer(x uint64) (n int) {
	return sovMsgServer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DVSResponsHandlerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DVSResponsHandlerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DVSResponsHandlerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestScriptIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestScriptIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestScriptIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = append(m.RequestId[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestId == nil {
				m.RequestId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestData = append(m.RequestData[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestData == nil {
				m.RequestData = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackFunctionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackFunctionId = append(m.CallbackFunctionId[:0], dAtA[iNdEx:postIndex]...)
			if m.CallbackFunctionId == nil {
				m.CallbackFunctionId = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskCreatedBlock", wireType)
			}
			m.TaskCreatedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskCreatedBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumNumbers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuorumNumbers = append(m.QuorumNumbers[:0], dAtA[iNdEx:postIndex]...)
			if m.QuorumNumbers == nil {
				m.QuorumNumbers = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumThresholdPercentage", wireType)
			}
			m.QuorumThresholdPercentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuorumThresholdPercentage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptId", wireType)
			}
			m.ScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScriptId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptParam", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptParam = append(m.ScriptParam[:0], dAtA[iNdEx:postIndex]...)
			if m.ScriptParam == nil {
				m.ScriptParam = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvanceDecode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AdvanceDecode = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestScriptResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestScriptResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestScriptResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIndex", wireType)
			}
			m.TaskIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptOutData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptOutData = append(m.ScriptOutData[:0], dAtA[iNdEx:postIndex]...)
			if m.ScriptOutData == nil {
				m.ScriptOutData = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgServer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgServer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataDigest = append(m.DataDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.DataDigest == nil {
				m.DataDigest = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgServer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgServer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgServer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgServer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgServer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgServer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgServer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgServer = fmt.Errorf("proto: unexpected end of group")
)
